const semesterTwo = [
  {
  "id": 1,
  "question": "Simplify F(x,y,z) = xy + x′yz′ + xyz′ + xy′z′ + xy′z and then draw its logic circuit diagram.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "Obtain the simplified expression in POS form for the following function using K-Map. (A,B,C,D) = Π (0, 2, 4, 5, 7, 8, 10, 13, 15)",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "Draw the circuit diagram of a 2-bit magnitude comparator that compares A₁A₀ and B₁B₀. The circuit has only one output L, such that L=1, if A>B.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "Express F(A, B, C) = A⊕B′⊕C in terms of AND, OR, NOT operators using Boolean algebra.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "Draw the logic circuit diagram of a staircase light controller. The light is controlled by two switches, one upstairs switch (U) and the other downstairs switch (D).",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 6,
  "question": "Draw the logic circuit diagram and characteristics table of JK flip flop.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 7,
  "question": "Design a combinational circuit that accepts 3-inputs (A,B,C) and generates the gray code of the inputs.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "Implement F(A, B, C, D) = Σ (0, 2, 4, 5, 7, 8, 9, 12, 13, 14, 15) using a 4×1 MUX. Use C, D as selection inputs of MUX.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 6
},
{
  "id": 9,
  "question": "Show the construction of a 3×8 decoder using two 2×4 decoders.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 4
},
{
  "id": 10,
  "question": "What is a shift register? Explain the difference between left shift and right shift operations with the help of an example. Draw the logic circuit diagram of a 4-bit bi-directional shift register.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "Express F(A,B,C) = A'B + AB' + B'C as “sum of minterms” and “product of maxterms.”",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "Simplify the expression A'B'C + (AB)' + BC using identities and theorems of Boolean algebra.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "Let F = X + Y'Z. Show that F'F = F + F'.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "Show the construction of a four-bit adder/subtractor circuit that can add/subtract two four-bit numbers A3A2A1A0 and B3B2B1B0. The add/subtract operation is controlled by a mode bit M, such that if M=0, the circuit should perform addition and if M=1, the circuit should perform subtraction.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "Show the construction of a 4×1 multiplexer using 2×1 multiplexers.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 6,
  "question": "Draw the truth table of F(X,Y,Z) = (X+Y).(X+Z'). Also draw the logic circuit diagram using NOR gates only.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 7,
  "question": "Obtain the simplified expression in SOP form for the following Boolean function using K-Map. F(A,B,C,D) = Σ(1,3,4,5,7,8,14,15)",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "Convert the equation (342)₈ = (142)ₓ to decimal number system, and then find base x.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-110",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "Draw the diagram of XOR gate, and prove that (A + B)(A + B') = A ⊕ B.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-110",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "Determine the truth table for F(A,B,C) = (A + B)', (A + B)', (A + B + C)'. Also, express F as sum of minterms.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-110",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "Given the following output equations for half adder, and full adder. Transform the equations of full adder using the output equations of half adder. Half adder: S = X ⊕ Y, C = XY. Full adder: S = X ⊕ Y ⊕ Z, C = XY + X'YZ + XY'Z + XYZ.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-110",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "Obtain the simplified expression in SOP form for the following function using K-Map. F(A,B,C,D) = A'B'C'D + A'B'D' + AB'C'D + BCD' + BCD' + AC.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-110",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 6,
  "question": "Implement F(A,B,C) = Σ(0,1,2,4,5,7) using 8×1 MUX. Keep two variables A and B as selection lines to the multiplexer. You must clearly label the diagram to get the full credit.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-110",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 7,
  "question": "Perform the following tasks for a Boolean function F(w,x,y,z) = (x + y + z)' + xyz + wyz. a) Draw truth table. b) Express F as “sum of minterms” and “product of maxterms.” c) Given F, find its minimum number of literals. d) Draw the logic circuit diagram of the simplified expression using NAND gates only.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-110",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "Design a combinational circuit for a parking place that has four parking lanes (A, B, C, D) for parking four cars. Each parking lane may either be occupied (1) or available (0). The status of each parking lane is detected by a sensor, and it is fed to a combinational circuit that generates an output F, such that F = 1 if the count of available parking lanes is equal to or greater than the count of occupied parking lanes.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-110",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 10
},
{
  "id": 9,
  "question": "Draw the logic circuit diagram, characteristic table, excitation table of JK flip flop. Show step-by-step construction of 2-bit DOWN counter using JK flip flops.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-110",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "Reduce the expression (x(y* + x)*)* + x + xy + wz to three literals using identities and theorems of Boolean Algebra.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "If (135)₈ → (17x)₁₆ → (1011)₂, then find x.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "Convert (1011.01)₂ to decimal number system.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "Obtain the simplified expression in Min. POS form using K-Map. F(A, B, C, D) = Σ(0, 2, 4, 5, 7, 8, 10, 11, 13, 15).",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "Given the following output equations for half subtractor and full subtractor; derive a relationship between half subtractor and full subtractor. Also draw a block diagram of Full Subtractor using Half Subtractors. X ⊕ Y, X’Y.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 6,
  "question": "Draw the truth table and logic circuit diagram of A⊕B using AND, OR, NOT gates.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 7,
  "question": "Implement F(A, B, C) = Σ(0, 1, 2, 4, 7) using 4×1 multiplexer with variable A, B as selection line.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 8,
  "question": "Design a circuit that will accept a 4-bit number (A, B, C, D) at its input and its output will be 1 iff at least two of its inputs are similar.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 10
},
{
  "id": 9,
  "question": "Perform the given tasks for a Boolean function F(A, B, C) = (A* + B). (B* + C). i) Draw the logic circuit diagram of F using NOR gates only. ii) Draw the truth table of F. iii) Represent F as product of maxterms. iv) Represent F as sum of products. v) Show that F + F’ = 1 using identities and theorems of Boolean algebra.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 10
},
{
  "id": 10,
  "question": "Draw the state transition table and state transition diagram for the sequential circuit shown in the figure below.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "Simplify F(w,x,y,z) = (x’y + z)’ + xy’z to minimum number of literals using identities and theorems of Boolean algebra. Also draw the logic circuit diagram of the simplified expression using NAND gates only.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "If (142)x = (57)₁₀, then find x. Convert (11010.1011)₂ to octal number system.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "Obtain the simplified expression in POS form for the following function using K-Map: (A,B,C,D) = Π(0, 2, 4, 5, 7, 8, 10, 13, 15).",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "Show the construction of a 3×8 decoder using two 2×4 decoders.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "Draw the circuit diagram of a 2-bit magnitude comparator that compares A₁A₀ and B₁B₀. The circuit has only one output S, such that S=1, if A<B.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 6,
  "question": "Draw the logic circuit diagram and characteristics table of RS flip flop.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "short",
  "marks": 5
},
{
  "id": 7,
  "question": "Design a digital circuit that accepts 4-bit number (A, B, C, D) at its input and its output will be 1 if the input is a palindrome. A palindrome includes sequences that remain the same in reverse order (e.g., 1001).",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "Implement the following functions using block diagrams of a decoder and appropriate external gates. F(x,y,z) = Π(0, 1, 2, 4, 6). G(x,y,z) = x’y’z + x’y + y’z + y.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 6
},
{
  "id": 9,
  "question": "Show the construction of a 4×1 multiplexer using 2×1 multiplexers.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 4
},
{
  "id": 10,
  "question": "Design a 3-bit synchronous counter using T flip flops, whose counting sequence is controlled by a control input x, such that: if x = 0: 0 → 1 → 2 → 3 → 4 → 5 → 6 → 7 → Repeat (Up Counter). if x = 1: 0 → 2 → 4 → 0 → 7 → 5 → 3 → Repeat.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "DC-121",
  "subject": "Digital Logic Design",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "Provide a brief description of each of the following, supported by an example: a) What is a binary operator? b) What is a posttest loop? c) How would a static local variable be useful?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-112N",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 6
},
{
  "id": 2,
  "question": "Write the output of the following program: bool s = true, t = true; s = !s || !t; t = !s && !t; printf(\"%d %d\", s, t);",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-112N",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 6
},
{
  "id": 3,
  "question": "Write the output of the following program: for (int i = 0; i < 7; i++) { if (i % 2 == 0) printf(\"%d\", 2 * i - 1); else if (i % 3 == 0) printf(\"%d\", i); else if (i % 5 == 0) printf(\"%d\", i + 1); else printf(\"%d\", i); }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-112N",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 6
},
{
  "id": 4,
  "question": "Write a program that calculates the average score of a student for five exams, displaying the result in decimal notation with one decimal place. The program should prompt the user to enter the score (out of 100) for each exam.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-112N",
  "subject": "Programming Fundamentals",
  "category": "long",
  "marks": 10
},
{
  "id": 5,
  "question": "The area of a parallelogram is the parallelogram’s base times its height. Write a program that asks the user to enter the base and height of two parallelograms. The program should then determine and display which parallelogram has the greater area, or state if both areas are the same.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-112N",
  "subject": "Programming Fundamentals",
  "category": "long",
  "marks": 10
},
{
  "id": 6,
  "question": "Write a program that calculates and displays a table showing the distance traveled by a river flowing at a rate of 2.3 meters per second. The table should include the distance traveled for each second up to 25 seconds.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "CC-112N",
  "subject": "Programming Fundamentals",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "What does a declaration do?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 6
},
{
  "id": 2,
  "question": "What happens in a do-while loop if the control condition is false initially?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 6
},
{
  "id": 3,
  "question": "What is a function definition?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 6
},
{
  "id": 4,
  "question": "Write the output produced by the following program: bool p = true, q = true; p = p || !q; q = p && q || !p && q; cout << p << \"\\t\" << q << endl;",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 6
},
{
  "id": 5,
  "question": "Write the output produced by the following program: for (int i = 1; i <= 7; i++) { if (i % 3 == 0) cout << i << \" \"; else if (i % 2 == 0) cout << i * i << \" \"; else if (i % 5 == 0) cout << i + 5 << \" \"; else cout << i << \" \"; }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 6
},
{
  "id": 6,
  "question": "Write a program that prompts the user to enter two integers and displays “Negative” if the difference between them is a negative number, and “Positive” if the difference between them is a positive number.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "long",
  "marks": 10
},
{
  "id": 7,
  "question": "Write a complete program that accepts or rejects applicants for temporary jobs. To qualify for a job, an applicant must be at least 20 years old and must have work experience. Additionally, the applicant must be able to type at least 25 words per minute. Accept all applicants who meet these requirements and display an appropriate message (Accepted or Rejected).",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "Write a program that lets the user enter a series of integers. The user should enter 0 to signal the end of the series. After all the numbers have been entered, the program should display the count of negative numbers entered by the user.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "long",
  "marks": 10
},
{
  "id": 9,
  "question": "#include <string>\n#include <iostream>\nusing namespace std;\nint main()\n{\n    int x = 10;\n    int y = 20;\n    int z = x + y;\n    cout << z;\n    return 0;\n}",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "coding",
  "marks": 10
},
{
  "id": 10,
  "question": "Write a program that solves the 3n+1 problem (Collatz conjecture). Start with an integer n. If n is even, divide by 2. If n is odd, multiply by 3 and add 1. Repeat until n = 1. For input n, the cycle-length of n is the number of numbers generated up to and including 1. Given any two numbers i and j, determine the maximum cycle length over all numbers between i and j, including both endpoints. Input: pairs of integers i and j (0 < i,j < 1,000,000). Output: For each pair, output i, j, and the maximum cycle length separated by spaces.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "coding",
  "marks": 15
},
{
  "id": 1,
  "question": "Consider the following code. What will be printed to the console when the second iteration of for loop runs? #include <stdio.h> #include <string.h> void display(int v) { v = v - 3; } int main() { int v = 15; while(v < 20 && v > 10) { display(v); printf(\"%d\", v--); printf(\",\"); } return 0; }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "How many times for loop in the following program will execute? #include <stdio.h> #include <string.h> int main() { int i = 4; for(i; i > 1; i--) printf(\"PF-2021\"); return 0; }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "Suppose you have an array: int arr2D[4][2] = {22,3,11,2}; What will be the output of printf(\"%d\", arr2D[1][1]);",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "What will be the output of the following program? #include <stdio.h> #include <string.h> int main() { FILE *file; char c[100]; file = fopen(\"file.txt\", \"w\"); fprintf(file, \"Dirilis Ertugrul is a Turkish historical fiction\"); fclose(file); file = fopen(\"file.txt\", \"r\"); fseek(file, 3, SEEK_SET); fscanf(file, \"%s\", c); printf(\"%s\", c); return 0; }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "#include<iostream>\nusing namespace std;\nint main()\n{\n    int C[5] = {5,7,9,6,5}; int j = 0;\n    cout << \"Postfix example\" << endl;\n    cout << \"contents before:\" << endl;\n    for (int i = 0; i < 5; i++)\n        cout << C[i] << \" \";\n    cout << endl;\n    C[j++] = 0;\n    cout << \"contents after:\" << endl;\n    for (int i = 0; i < 5; i++)\n        cout << C[i] << \" \";\n    cout << endl;\n    return 0;\n}",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "coding",
  "marks": 7
},
{
  "id": 6,
  "question": "#include<iostream>\nusing namespace std;\nint main()\n{\n    char a[6];\n    cin >> a;\n    for(int i=0; i<7; i++)\n        cout << \"index \" << i << \" \" << a[i] << endl;\n    return 0;\n}",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "coding",
  "marks": 8
}, {
  "id": 7,
  "question": "Print the following pattern on the screen:\n1 2 3 4 5 6\n6 8 10 12 14 16\n16 19 22 25 28 31\n31 35 39 43 47 51\n51 56 61 66 71 76\n76 82 88 94 100 106",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "coding",
  "marks": 10
} ,
{
  "id": 1,
  "question": "What will be the output of the following program? #include <stdio.h> #include <string.h> int main() { int arr[2][4]={1,2,3,4,1,2,3,4}; int i=0; printf(\"%d\",arr[i++][i]); return 0; }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "Consider the following code. How many times if statement inside the while loop will execute? #include <stdio.h> #include <string.h> int main() { int a=12,b=14; while(a>10) { printf(\"\\n\\n\"); if(a==b) b=b+1; a=b-(b-a); } return 0; }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "Write a C program that solves the 3n+1 problem (Collatz conjecture). Start with an integer n. If n is even, divide by 2. If it is odd, multiply by 3 and add 1. Repeat until n = 1. For input n, the cycle-length of n is the number of numbers generated up to and including 1. Given any two numbers i and j, determine the maximum cycle length over all numbers between i and j, including both endpoints. Input: pairs of integers i and j (0 < i,j < 1,000,000). Output: For each pair, output i, j, and the maximum cycle length separated by spaces.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "coding",
  "marks": 10
}, {
  "id": 1,
  "question": "Program 4: #include<iostream> using namespace std; int main() { char ch = 'a'; int i = 10; while ((i <= 15) && (ch != 99)) { ch = ch + 1; i = i - 1; cout << i << \" \" << ch << endl; } return 0; }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "coding",
  "marks": 10
},
{
  "id": 2,
  "question": "Program 5: #include<iostream> using namespace std; int add(int, int); int sub(int, int); int main() { int a = 2, b = 3; cout << sub(add(a, b), add(a, b)); return 0; } int add(int a, int b) { static int s = a; int r = sub(sub(a, b), s); s = b; a = r; return r; } int sub(int a, int b) { return (a - b); }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "coding",
  "marks": 10
},
{
  "id": 3,
  "question": "Write a program that calculates and displays the sum of consecutive integers from a user-defined starting limit to a user-defined ending limit. For example, if the starting limit is 3 and the ending limit is 7, the program should compute and display 3 + 4 + 5 + 6 + 7 = 25.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "long",
  "marks": 10
},
{
  "id": 4,
  "question": "Write a function called countOccurrences that takes three parameters: an array of integers, its size, and an integer key. The function should search the array for occurrences of the key element and return the total count of occurrences found. If the key is not present in the array, the function should return -1.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "long",
  "marks": 10
},
{
  "id": 5,
  "question": "Write a function named sum that calculates the sum of a variable number of integer numbers passed as arguments. Provide the complete definition of this function to correctly execute the following calls: cout << sum(1, 2); // 3, cout << sum(1, 2, 3); // 6, cout << sum(1, 2, 3, 2); // 8.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "What presentation skills are required to sell a software to a company?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "How does tone affect oral presentation?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "How body language like walking, sitting and standing affect your personality?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "What is difference between memo and letter?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "Why reading skills are necessary to be a good communicator?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 6,
  "question": "What is mutual understanding in a communication process?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 7,
  "question": "What are the strategies of time management? Discuss with examples.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "Write an application to your boss for an increment in your salary.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 9,
  "question": "Write a memo to your assistant and inform him that he has to prepare a product presentation for a new client. Give him details what to include and how to present.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
} ,
{
  "id": 1,
  "question": "How time zones effect the communication in an organization?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 6
},
{
  "id": 2,
  "question": "Differentiate between physical and personal space with an example.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 6
},
{
  "id": 3,
  "question": "What is the difference between a memo written to a superior and a subordinate?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 6
},
{
  "id": 4,
  "question": "How does cultural awareness can create effective oral communication, give an example.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 6
},
{
  "id": 5,
  "question": "When should we use graphs and maps; and when should we use pictures and movie clips in a presentation?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 6
},
{
  "id": 6,
  "question": "Write a memo to your boss and inform him/her about the success of your company’s new product in the market.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 7,
  "question": "How can a conflict in a group is resolved, discuss the different ways to reach a resolution.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "Write an application to your boss and request him to transfer you to the branch near to your home with a valid reason for the transfer.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Fall",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "Sample Input: 1 10, 100 200, 201 210, 900 1000. Sample Output: 1 10 20, 100 200 125, 201 210 89, 900 1000 174.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "coding",
  "marks": 10
},
{
  "id": 2,
  "question": "For each of the following, write C statements that perform the specified task: a) Declare a built-in array of type int called values with five elements, initialized to even integers from 2 to 10. Assume SIZE = 5. b) Declare a pointer vPtr that points to an object of type unsigned int. c) Use a for statement to display the elements of values using array subscript notation. d) Write two separate statements that assign the starting address of values to vPtr. e) Use a for statement to display the elements of values using pointer/offset notation. f) Use a for statement to display the elements of values using pointer/offset notation with the array’s name as the pointer. g) Use a for statement to display the elements of values by subscripting the pointer to the array.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 10
},
{
  "id": 3,
  "question": "Write a C program that prints the following pattern on the screen using nested loops:\n1 2 3 4 5 6\n6 8 10 12 14 16\n16 19 22 25 28 31\n31 35 39 43 47 51\n51 56 61 66 71 76\n76 82 88 94 100 106",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "coding",
  "marks": 10
},
 {
  "id": 1,
  "question": "Write the output of the following program: int main() { int a = 6, b = 12, c = 2, d = 8; cout << a++ + ++b + c - d << endl; cout << (c-- + (b - d)) << endl; cout << (a + b % a * c) << endl; return 0; }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 6
},
{
  "id": 2,
  "question": "Write the output of the following program: int main() { bool flagT = true, flagF = false; float f1 = .001f, f2 = 0.1f; if (f1 < f2) if ((flagF && flagT) || !(flagF && flagT)) cout << \"**\" << endl; else cout << \"##\" << endl; return 0; }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 6
},
{
  "id": 3,
  "question": "Write the output of the following program: int main() { char grade = 'C'; switch (grade) { case 'A': cout << \"80\" << endl; break; case 'B': cout << \"70\" << endl; break; case 'C': cout << \"60\" << endl; break; case 'D': cout << \"50\" << endl; break; default: cout << \"F\" << endl; break; } }",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2024,
  "term": "Spring",
  "course_code": "CC-112",
  "subject": "Programming Fundamentals",
  "category": "short",
  "marks": 6
},
{
  "id": 1,
  "question": "Why do you need to understand the purposes, audience, and the context for the message to know whether a specific set of words will work?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "Briefly describe a miscommunication you’ve had with a co-worker/ fellow college student/ friend or family member. Can you identify what barrier(s) prevented your successful communication?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "How significant is the occasion for speaking in relation to the audience? Elaborate.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "Describe the significance of effective listening and its outcomes?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "How does good communication in an organization improve employees’ attitude and performances?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 6,
  "question": "Why does an oral presentation have to be simpler than a written message to the same audience? Justify.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 7,
  "question": "Is the ability to communicate more important to the successful performance of a supervisor’s job than to that of a company president’s job? Defend your answer.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "You are the marketing manager of a company. Write a short memo to your boss and predict latest market trend for the new product of your company.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 9,
  "question": "What are some of the intercultural communication issues to consider when deciding whether to accept an overseas job with a firm? A job in your own country with a local branch of a foreign owned firm?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
}, {
  "id": 1,
  "question": "How would you cater to the different needs of your audience while sending the message?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "Differentiate between a business letter and a memorandum.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "What problems could result from using visual aids during your presentations?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "Explain briefly whether you agree or disagree with the notion that 'technology will largely replace the need for humans to communicate face to face'.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "How do you obtain feedback from a reader? What difference does feedback make to a writer?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 6,
  "question": "Why do writing and speaking become even more important as people rise in the organization?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 7,
  "question": "Environmental space refers to how we perceive, construct and manipulate physical space in business and professional settings. Describe the impression you wish to make on your customers and then construct an ideal office arrangement and reception area in detail, mentioning furniture setting, color scheme of the office etc.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "Give an example and supporting evidence that reinforces the guiding principle that nonverbal behavior always communicates.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 9,
  "question": "Write a memo to your assistant and ask him to arrange a dinner with a client at a good restaurant. Tell him to share dinner details with the client.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2022,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "What is the definition of nonverbal communication?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 6
},
{
  "id": 2,
  "question": "Why meetings are important in decision making process?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 6
},
{
  "id": 3,
  "question": "How time acts an important nonverbal cue, explain with example.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 6
},
{
  "id": 4,
  "question": "What points should be kept in mind before writing a message or initiating communication with customer for the first time?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 6
},
{
  "id": 5,
  "question": "How should we know that what visuals will work for a games application?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 6
},
{
  "id": 6,
  "question": "Write a memo to your employees and inform them about the new policy for taking leaves. Give details of the policy.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 7,
  "question": "How group meetings help everyone to discuss and decide a solution, explain with an example.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "Write a letter to a client and inform him/her that the bank has extended their credit card limit.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "Why is it important to use simple and precise language?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GENG-201",
  "subject": "Expository Writing",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "How do visuals or examples help engage a specific audience?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GENG-201",
  "subject": "Expository Writing",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "How can a writer maintain integrity in their work?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GENG-201",
  "subject": "Expository Writing",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "How can you make an introduction clear and engaging?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GENG-201",
  "subject": "Expository Writing",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "How can plagiarism affect the credibility of your writing?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GENG-201",
  "subject": "Expository Writing",
  "category": "short",
  "marks": 5
},
{
  "id": 6,
  "question": "How can setting goals improve your writing process?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GENG-201",
  "subject": "Expository Writing",
  "category": "short",
  "marks": 5
},
{
  "id": 7,
  "question": "What strategies can a writer use in the introduction to engage the reader’s interest without inserting personal opinions or arguments?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GENG-201",
  "subject": "Expository Writing",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "Why is it important for writers to maintain honesty and accuracy when presenting information in expository writing, and what are the consequences of failing to do so?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GENG-201",
  "subject": "Expository Writing",
  "category": "long",
  "marks": 10
},
{
  "id": 9,
  "question": "What strategies can writers use during the revising stage to improve the content, structure, and clarity of their writing, and how does this step enhance the overall quality of the text?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GENG-201",
  "subject": "Expository Writing",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "What presentation skills are required to sell a software to a company?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "How does tone affect oral presentation?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "How body language like walking, sitting and standing affect your personality?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "What is difference between memo and letter?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "Why reading skills are necessary to be a good communicator?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 6,
  "question": "What is mutual understanding in a communication process?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "short",
  "marks": 5
},
{
  "id": 7,
  "question": "What are the strategies of time management? Discuss with examples.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "Write an application to your boss for an increment in your salary.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 9,
  "question": "Write a memo to your assistant and inform him that he has to prepare a product presentation for a new client. Give him details what to include and how to present.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2023,
  "term": "Spring",
  "course_code": "GE-164",
  "subject": "Communication & Presentation Skills",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "قرآن مجید میں کل کتنی سورتیں ہیں؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 2,
  "question": "اسلام میں ایمان کی کتنی اقسام ہیں؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 3,
  "question": "حضرت محمد ﷺ کی ولادت کب ہوئی؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 4,
  "question": "حضرت محمد ﷺ کی وفات کب ہوئی؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 5,
  "question": "حضرت محمد ﷺ کے والد کا نام کیا تھا؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 6,
  "question": "حضرت محمد ﷺ کے دادا کا نام کیا تھا؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 7,
  "question": "حضرت محمد ﷺ کی والدہ کا نام کیا تھا؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 8,
  "question": "حضرت محمد ﷺ کے چچا کا نام کیا تھا؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 9,
  "question": "حضرت محمد ﷺ کے کتنے بیٹے تھے؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 10,
  "question": "حضرت محمد ﷺ کے کتنی بیٹیاں تھیں؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 11,
  "question": "حضرت محمد ﷺ کے کتنی ازواج تھیں؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 12,
  "question": "حضرت محمد ﷺ کے کتنے صحابہ کرام تھے؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 13,
  "question": "حضرت محمد ﷺ کی پہلی وحی کہاں نازل ہوئی؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 14,
  "question": "حضرت محمد ﷺ کی ہجرت کب ہوئی؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 15,
  "question": "خود اللہ میں ایمان اور توحید پر ایمان میں کیا فرق ہے؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 2
},
{
  "id": 16,
  "question": "اسلام کے بنیادی عقائد کے متعلق تفصیلی جواب تحریر کریں۔",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "long",
  "marks": 10
},
{
  "id": 17,
  "question": "اسلام میں نظام تعلیم کے بارے میں قرآن کی تعلیمات بیان کیجئے۔",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "long",
  "marks": 10
},
{
  "id": 18,
  "question": "نبی کریم ﷺ نے تبلیغ کے لیے کن وسائل استعمال کیے؟",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "long",
  "marks": 10
},
{
  "id": 19,
  "question": "اسلام کے معاشرتی نظام پر روشنی ڈالیں۔",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2021,
  "term": "Fall",
  "course_code": "GE-163",
  "subject": "Islamic Studies",
  "category": "long",
  "marks": 10
},
{
  "id": 1,
  "question": "Describe three virtues of the Holy Quran.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "GISL-101",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 5
},
{
  "id": 2,
  "question": "Write a blessed hadith with translation on protection of hadith.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "GISL-101",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 5
},
{
  "id": 3,
  "question": "Which person is said to be poor in the hadith.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "GISL-101",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 5
},
{
  "id": 4,
  "question": "Write the names of the Prophet’s ﷺ daughters.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "GISL-101",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 5
},
{
  "id": 5,
  "question": "When did the Battle of Uhud take place and explain two reasons for it?",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "GISL-101",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 5
},
{
  "id": 6,
  "question": "Write only the names of the five main sources of Islamic jurisprudence.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "GISL-101",
  "subject": "Islamic Studies",
  "category": "short",
  "marks": 5
},
{
  "id": 7,
  "question": "Give translation and explanation of the following Hadith: عن أبي سعيد رضي الله عنه قال قال النبي صلى الله عليه وسلم: \"إياكم والظن فإن الظن أكذب الحديث ولا تجسسوا ولا تحسسوا ولا تنافسوا ولا تحاسدوا ولا تباغضوا ولا تدابروا وكونوا عباد الله إخوانا\"",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "GISL-101",
  "subject": "Islamic Studies",
  "category": "long",
  "marks": 10
},
{
  "id": 8,
  "question": "Write a detailed note on the Caliph Hazrat Ali.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "GISL-101",
  "subject": "Islamic Studies",
  "category": "long",
  "marks": 10
},
{
  "id": 9,
  "question": "Write in detail on the status of woman in Islam.",
  "index": true,
  "trim": true,
  "type": "past-paper",
  "year": 2025,
  "term": "Spring",
  "course_code": "GISL-101",
  "subject": "Islamic Studies",
  "category": "long",
  "marks": 10
}
]