import { v4 as uuidv4 } from "uuid";
const semesterFive = [
{
    id: uuidv4(),
    question: "Define an Operating System and explain its major functions.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "What is a system call? Explain its purpose with examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Differentiate between a process and a thread.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "What is a deadlock? State its four necessary conditions.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Explain paging and its advantages.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Explain process scheduling algorithms (FCFS, SJF, Priority and Round Robin) with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Discuss memory management in detail. Explain contiguous memory allocation, paging, segmentation and virtual memory.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311",
    Subject: "Operating Systems"
},

{
    id: uuidv4(),
    question: "Explain the role of an Operating System in computer systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Define interprocess communication (IPC).",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "What is multithreading? State its advantages.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Explain the critical section problem.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Differentiate between paging and segmentation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Discuss synchronization techniques. Explain semaphores, mutex locks and critical section with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Explain file system organization. Discuss directory structure, file allocation methods and free space management.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311",
    Subject: "Operating Systems"
},

{

    id: uuidv4(),
    question: "What is process scheduling? Why is it important in an operating system?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Define a multithreaded process. State any two advantages of multithreading.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "What is swapping? Explain its purpose in memory management.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "What is virtual memory? Why is it used?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Define a file system. What are its main components?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Explain deadlocks in detail. Discuss the necessary conditions, deadlock prevention, avoidance, detection and recovery techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Explain virtual memory management. Discuss demand paging, page replacement, thrashing and memory-mapped files.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311",
    Subject: "Operating Systems"
},

{
    id: uuidv4(),
    question: "What is interprocess communication (IPC)? Name its two basic models.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Define synchronization. Why is it necessary in operating systems?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "What is demand paging? Explain briefly.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Differentiate between logical address and physical address.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "What is disk scheduling? Name any four disk scheduling algorithms.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Explain thread scheduling and multiprocessor scheduling. Compare user-level threads and kernel-level threads.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Discuss file system implementation in detail. Explain directory implementation, disk structure, free space management and swap space management.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311",
    Subject: "Operating Systems"
},

// ====================== 2025 ======================


{
    id: uuidv4(),
    question: "What is a system call? Explain its types.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Define synchronization hardware and explain its purpose.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "What is thrashing? How does it affect system performance?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "What is a virtual machine? State its advantages.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Explain operating system security and system protection.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Discuss process management in detail. Explain process states, process scheduling, interprocess communication (IPC), multithreading, and thread scheduling with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311",
    Subject: "Operating Systems"
},
{
    id: uuidv4(),
    question: "Explain disk management and file systems in detail. Discuss disk structure, disk scheduling algorithms, directory implementation, free space management, swap space management, and memory-mapped files.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311",
    Subject: "Operating Systems"
},

// ====================== 2021 ======================

{
    id: uuidv4(),
    question: "What is virtualization? Explain the role of a hypervisor.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Explain the Linux file hierarchy standard (FHS).",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between hard links and soft links.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Explain the purpose of the chmod and chown commands.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the mount and umount commands in Linux?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Explain the Linux file system architecture. Discuss the boot block, superblock, inode block, data blocks, and file system mounting with suitable Linux commands.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Discuss Linux file permissions in detail. Explain standard permissions, special permissions (SUID, SGID, Sticky Bit), umask, chmod, and chown with examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},

// ====================== 2022 ======================

{
    id: uuidv4(),
    question: "What is an inode in the Linux file system?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Explain the use of the fsck command.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the stty command?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Define device files in Linux.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the systemctl command?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Explain Linux booting process in detail. Discuss BIOS/UEFI, MBR, Boot Loader, Kernel Initialization, and systemd process.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Discuss Linux service management using systemd. Explain service unit files, target unit files, systemctl commands, and the creation of a basic Linux service.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
// ====================== 2023 ======================

{
    id: uuidv4(),
    question: "What is the Linux System Call Interface?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the GNU gcc compiler in Linux?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between fork() and execl() system calls.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "What is input and output redirection in Linux?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Define Pipes and FIFOs in Linux.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Explain Linux process creation and termination. Discuss getpid(), getppid(), fork(), wait(), exit(), and execl() system calls with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Discuss Linux system programming in detail. Explain the program file structure, object file analysis using objdump and readelf, and file management in Linux.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},

// ====================== 2024 ======================

{
    id: uuidv4(),
    question: "What are signals in Linux?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between synchronous and asynchronous signals.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the kill command in Linux?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "What is pthread_create() used for?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Explain the purpose of pthread_mutex_lock() and pthread_mutex_unlock().",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Discuss Inter-Process Communication (IPC) in Linux. Explain Pipes, FIFOs, Sockets, and their practical applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Explain Linux signals in detail. Discuss signal handling, signal delivery, standard and real-time signals, important signal types, and the kill command.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
// ====================== 2025 ======================

{
    id: uuidv4(),
    question: "What is CPU affinity in Linux scheduling?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the schedtool command in Linux?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Define POSIX threads (Pthreads).",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between mkfs and mke2fs commands.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "What is thread synchronization? Why is pthread_mutex_t used?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Explain multithreading in Linux using the POSIX pthread library. Discuss pthread_create(), pthread_join(), pthread_exit(), mutex variables, mutex locking/unlocking, and CPU scheduling parameters with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},
{
    id: uuidv4(),
    question: "Discuss Linux file system creation and administration in detail. Explain the use of mkfs, mke2fs, mkntfs, mkfs.fat, mkfs.minix, file system integrity checking (fsck), partition formatting, and Linux file management tools.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-311L",
    Subject: "Operating Systems Lab"
},

// ====================== 2021 ======================

{
    id: uuidv4(),
    question: "Define an algorithm and explain its characteristics.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321", 
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "What is Big-O notation? Explain its significance.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Differentiate between Big-O and Big-Θ notations.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "What is a loop invariant? Why is it important?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Define recurrence relation with an example.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Explain asymptotic notations in detail. Discuss Big-O, Big-Ω, Big-Θ, little-o, and little-ω with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Discuss algorithm analysis in detail. Explain input size, time complexity, space complexity, sorting algorithm analysis, and loop invariants.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},

// ====================== 2022 ======================

{
    id: uuidv4(),
    question: "What is Divide and Conquer strategy?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Explain the Brute Force algorithm design technique.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Differentiate between Merge Sort and Quick Sort.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "What is the Greedy approach? Give one application.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Define Dynamic Programming.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Explain Divide and Conquer in detail. Discuss Merge Sort and Quick Sort algorithms with complexity analysis.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Discuss Greedy and Dynamic Programming approaches. Compare both techniques with suitable examples and applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
// ====================== 2023 ======================

{
    id: uuidv4(),
    question: "What is a heap? Mention its applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Define a search tree.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "What is hashing? State its advantages.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Define graph traversal.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "What is the shortest path problem in graph algorithms?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Explain graph algorithms in detail. Discuss graph traversal techniques and shortest path algorithms with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Discuss heaps, search trees, and hashing in detail. Explain their operations, advantages, disadvantages, and applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},

// ====================== 2024 ======================

{
    id: uuidv4(),
    question: "What is string matching? Give one application.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Define sparse graph.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "What are complexity classes?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Differentiate between time complexity and space complexity.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Explain the importance of recurrence relations in algorithm analysis.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Explain string matching algorithms in detail. Discuss their working principles, complexity, and practical applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Discuss complexity classes in detail. Explain P, NP, NP-Complete, and NP-Hard problems with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
// ====================== 2025 ======================

{
    id: uuidv4(),
    question: "Differentiate between Big-O and Big-Ω notations.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "What is the role of recurrence relations in Divide and Conquer algorithms?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Define Dynamic Programming and mention its key characteristics.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "What is hashing? Explain the concept of hash collisions.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "What is the importance of graph algorithms in computer science?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Discuss the major algorithm design techniques in detail. Explain Brute Force, Divide and Conquer, Greedy Method, and Dynamic Programming with suitable examples and compare their efficiencies.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
{
    id: uuidv4(),
    question: "Explain graph algorithms in detail. Discuss shortest path algorithms, sparse graphs, string matching techniques, and complexity classes with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-321",
    Subject: "Design & Analysis of Algorithms"
},
// ====================== 2021 ======================

{
    id: uuidv4(),
    question: "Differentiate between a compiler and an interpreter.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "State the major phases of a compiler.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "What is lexical analysis? What is the output of a lexical analyzer?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "What is the purpose of syntax analysis in a compiler?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Differentiate between tokens and lexemes with examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Explain the organization of a compiler. Discuss each compilation phase from lexical analysis to code generation with the help of a suitable block diagram.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Describe lexical analysis and syntax analysis in detail. Explain their responsibilities, outputs, common errors, and interaction within the compilation process.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},

// ====================== 2022 ======================

{
    id: uuidv4(),
    question: "Why is a symbol table required in compiler construction?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Differentiate between top-down and bottom-up parsing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "What is recursive descent parsing?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "What is semantic analysis? State its purpose.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "What is type checking? Why is it performed during compilation?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Compare top-down and bottom-up parsing techniques. Explain their working principles, advantages, limitations, and suitable applications with examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Explain semantic analysis in detail. Discuss type checking, semantic errors, symbol table management, and the role of the semantic analyzer in a compiler.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
// ====================== 2023 ======================

{
    id: uuidv4(),
    question: "Define parsing. Why is it required in compiler construction?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "What is a parse tree? How is it used by a compiler?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "State any four responsibilities of a lexical analyzer.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Differentiate between lexical errors and syntax errors.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "What is error recovery in compiler design?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Discuss parsing techniques used in compiler construction. Explain LL and LR parsing methods, their working principles, advantages, limitations, and suitable applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Explain compiler error handling in detail. Discuss different types of compilation errors along with suitable error detection and recovery techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},

// ====================== 2024 ======================

{
    id: uuidv4(),
    question: "What is object code generation?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "What is code optimization? Why is it necessary?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Differentiate between source code and object code.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "State the objectives of code optimization.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Why is object code generation considered the final phase of a compiler?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Explain object code generation in detail. Discuss intermediate code generation, target code generation, and the role of machine-independent and machine-dependent optimizations.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Discuss code optimization techniques in compiler construction. Explain the objectives, types, and benefits of optimization with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
// ====================== 2025 ======================

{
    id: uuidv4(),
    question: "Why are lexical and syntax analysis performed separately in a compiler?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "What is the role of a parser in compiler construction?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Differentiate between compile-time errors and run-time errors.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "What is the purpose of type checking during semantic analysis?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "State any four objectives of compiler optimization.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Describe the complete compilation process from source program to object code. Explain the role of lexical analysis, syntax analysis, semantic analysis, intermediate code generation, code optimization, and object code generation with a suitable diagram.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
{
    id: uuidv4(),
    question: "Compare compiler and interpreter in detail. Discuss their architecture, execution process, advantages, limitations, error handling, and practical applications with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "DC-322",
    Subject: "Compiler Construction"
},
// ====================== 2021 ======================

{
    id: uuidv4(),
    question: "Differentiate between the database approach and the traditional file-based system.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "What is data independence? Why is it important in DBMS?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Explain the purpose of the three-schema architecture.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Define a relation, tuple, and attribute in the relational model.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "What is a primary key? How does it differ from a foreign key?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Discuss the architecture of a Database Management System. Explain the three-schema architecture, data independence, and advantages of the database approach over the file-based system.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Explain the relational data model in detail. Discuss relations, attributes, tuples, domains, relation instances, keys, and integrity constraints with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215",
    Subject: "Database Systems"
},

// ====================== 2022 ======================

{
    id: uuidv4(),
    question: "What are integrity constraints? Why are they used in databases?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "What is the purpose of the Selection operation in relational algebra?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Differentiate between Selection and Projection operations.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "What is a Cartesian Product in relational algebra?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "State any four types of SQL joins.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Explain relational algebra in detail. Discuss Selection, Projection, Cartesian Product, and different types of Join operations with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Discuss keys and integrity constraints in relational databases. Explain primary key, candidate key, alternate key, foreign key, and referential integrity with examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215",
    Subject: "Database Systems"
},
// ====================== 2023 ======================

{
    id: uuidv4(),
    question: "What is normalization? Why is it required in database design?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Define functional dependency with a suitable example.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Differentiate between 2NF and 3NF.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "What is an entity-relationship (ER) model?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Differentiate between an entity and a relationship.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "A poorly designed database often suffers from insertion, deletion, and update anomalies. Explain the process of normalization and discuss First Normal Form (1NF), Second Normal Form (2NF), Third Normal Form (3NF), and BCNF with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Design an Entity-Relationship (ER) diagram for a university library management system. Clearly identify entities, attributes, relationships, and cardinality constraints.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215",
    Subject: "Database Systems"
},

// ====================== 2024 ======================

{
    id: uuidv4(),
    question: "What is the purpose of the GROUP BY clause in SQL?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Differentiate between WHERE and HAVING clauses.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "What is a subquery? Mention one practical use.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Name any four aggregate functions available in SQL.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Why are SQL joins used? Explain briefly.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Write SQL queries to retrieve meaningful information from a relational database. Your solution should demonstrate the use of joins, nested queries, GROUP BY, HAVING, and aggregate functions.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "A company database contains Employee, Department, and Project tables. Write SQL statements to perform different join operations and explain the expected output of each query.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215",
    Subject: "Database Systems"
},
// ====================== 2025 ======================

{
    id: uuidv4(),
    question: "What is concurrency control? Why is it important in a multi-user database environment?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Differentiate between database backup and database recovery.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "What is an index? How does it improve query performance?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "What is NoSQL? State any four features of NoSQL databases.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Why are indexes created in a database? Explain with a suitable example.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "A banking application allows thousands of users to access the same database simultaneously. Explain how concurrency control mechanisms maintain data consistency. Also discuss common concurrency problems and techniques used to resolve them.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215",
    Subject: "Database Systems"
},
{
    id: uuidv4(),
    question: "Modern organizations increasingly use both relational and non-relational databases. Compare traditional relational databases with NoSQL systems. Also explain the role of indexes, backup, and recovery in ensuring database performance and reliability.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215",
    Subject: "Database Systems"
},
// ====================== 2021 ======================

{
    id: uuidv4(),
    question: "Write the syntax of the SELECT statement with a suitable example.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the WHERE clause in SQL?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between column alias and table alias.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Explain the use of the ORDER BY clause with an example.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the DESCRIBE (DESC) command in SQL?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Write SQL queries to retrieve records from a database using the SELECT statement. Demonstrate the use of arithmetic expressions, aliases, comparison operators, logical operators, NULL values, and ORDER BY clause.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "A database contains Student and Course tables. Write SQL statements to filter and sort records using WHERE, logical operators, comparison operators, and ORDER BY. Explain the output of each query.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},

// ====================== 2022 ======================

{
    id: uuidv4(),
    question: "What is the purpose of single-row functions in SQL?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Name any four character functions available in SQL.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between SUM() and AVG() functions.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the GROUP BY clause?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Why is the HAVING clause used in SQL?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Write SQL queries using character, numeric, date, and conversion functions. Demonstrate the use of aggregate functions, GROUP BY, and HAVING clauses with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "A company database stores employee salary records. Write SQL statements to calculate totals, averages, standard deviation, and variance while grouping data by department. Explain the result of each query.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
// ====================== 2023 ======================

{
    id: uuidv4(),
    question: "Differentiate between INNER JOIN and LEFT OUTER JOIN.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "What is a self join? Mention one practical application.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of a subquery in SQL?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between pairwise and non-pairwise comparison in subqueries.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Why are aliases used while performing SQL joins?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Write SQL queries to demonstrate Cross Join, Natural Join, Equi Join, Non-Equi Join, Left Outer Join, Right Outer Join, and Self Join. Explain the output of each query using suitable tables.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "A university database contains Student, Department, and Course tables. Write SQL queries using single-row and multiple-row subqueries to retrieve meaningful information. Explain the logic of each query.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},

// ====================== 2024 ======================

{
    id: uuidv4(),
    question: "What is the purpose of the CREATE TABLE statement?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between PRIMARY KEY and UNIQUE constraint.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the FOREIGN KEY constraint?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "When is the ALTER TABLE statement used?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between DELETE and DROP statements.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Create a database table for an online shopping system by applying appropriate constraints. Write SQL statements to create, modify, and delete database objects using CREATE, ALTER, and DROP commands.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Write SQL statements to perform INSERT, UPDATE, and DELETE operations on a Student Management System database. Explain how different constraints maintain data integrity during these operations.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
// ====================== 2025 ======================

{
    id: uuidv4(),
    question: "What is a database view? Mention two advantages of using views.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between an index and a sequence in SQL.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the CREATE USER statement?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Why are the GRANT and REVOKE commands used in SQL?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "How do indexes improve the performance of SQL queries?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "A software company wants to improve the performance and security of its database. Write SQL statements to create and manage views, sequences, and indexes. Explain how each object contributes to database efficiency and security.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
{
    id: uuidv4(),
    question: "Design a user management strategy for a university database. Write SQL commands to create users, assign privileges, organize users into roles/groups, and use GRANT and REVOKE statements to control database access.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "CC-215L",
    Subject: "Database Systems Lab"
},
// ====================== 2021 ======================

{
    id: uuidv4(),
    question: "Differentiate between a website and a web application.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What is the role of HTTP in web applications?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What is virtual hosting in a web server?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "State any four application services provided by the TCP/IP protocol suite.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Why is caching support important in web servers?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Explain the architecture of a web application. Discuss the role of TCP/IP application services, HTTP protocol, web servers, virtual hosting, caching support, and extensibility in modern web systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "A software company plans to deploy multiple websites on a single server. Explain the working of web servers, virtual hosting, chunked transfer encoding, and caching mechanisms with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331",
    Subject: "Web Technologies"
},

// ====================== 2022 ======================

{
    id: uuidv4(),
    question: "Differentiate between HTML5 and XHTML.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What is SGML? How is it related to HTML?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What are the advantages of CSS3 in web development?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What is XML? Mention two practical applications of XML.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Differentiate between XML and HTML.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Explain HTML5 and CSS3 in the context of modern web development. Discuss their features, advantages, and how they contribute to responsive and interactive web applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Discuss XML technologies in detail. Explain XML, XHTML, XHTML-MP, document structure, and their applications in web development with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
// ====================== 2023 ======================

{
    id: uuidv4(),
    question: "Differentiate between SOAP and REST web services.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What is the purpose of HTTP request and HTTP response messages?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Why are cookies used in web applications?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What is the purpose of server configuration in web applications?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What is meant by dynamic content delivery?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Compare SOAP and REST web services. Explain their architecture, communication mechanisms, advantages, limitations, and suitable application areas with examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Explain how a web server processes client requests. Discuss HTTP request processing, HTTP response generation, cookies, dynamic content delivery, and server configuration in modern web applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331",
    Subject: "Web Technologies"
},

// ====================== 2024 ======================

{
    id: uuidv4(),
    question: "What is AJAX? Why is it widely used in modern web applications?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Differentiate between JavaScript and DHTML.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What is JSON? Mention its advantages in web development.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What is the role of JavaScript in client-side web development?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "State any four features of AJAX.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Explain the role of JavaScript, DHTML, AJAX, and JSON in the development of interactive web applications. Support your answer with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Design the architecture of a dynamic web application that exchanges data asynchronously with the server. Explain how AJAX, JSON, JavaScript, and HTTP work together to improve user experience.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
// ====================== 2025 ======================

{
    id: uuidv4(),
    question: "What is Search Engine Optimization (SEO)? Why is it important for web applications?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What is the purpose of XML Query Language?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Differentiate between traditional web applications and modern web application frameworks.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "What is the Semantic Web? State its key objectives.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Why is server security essential in web application development?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Discuss the principles of Search Engine Optimization (SEO). Explain both on-page and off-page optimization techniques and evaluate their role in improving the visibility and performance of modern web applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
{
    id: uuidv4(),
    question: "Modern web applications demand security, scalability, and intelligent data processing. Discuss server security, Semantic Web, XML Query Language, and emerging web application frameworks. Explain how these technologies influence the future of web development.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331",
    Subject: "Web Technologies"
},
// ====================== 2021 ======================

{
    id: uuidv4(),
    question: "Differentiate between JDK, JRE, and JVM.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "What is method overloading in Java?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between method overloading and method overriding.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of interfaces in Java?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "State any four primitive data types available in Java.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Write a Java program to demonstrate the use of classes, objects, methods, constructors, interfaces, method overloading, and method overriding. Explain the output of the program.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Develop a menu-driven Java application using control structures and methods. The program should perform multiple operations and demonstrate the concepts of object-oriented programming.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},

// ====================== 2022 ======================

{
    id: uuidv4(),
    question: "What is Event Handling in Java?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of Swing components in Java?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between AWT and Swing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Why is exception handling used in Java?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the try-catch block?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Develop a Java GUI application using Swing components. Implement event handling to perform user-defined operations and explain the working of the application.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Write a Java program that demonstrates exception handling and file handling. Use appropriate exception handling techniques to prevent abnormal program termination.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
// ====================== 2023 ======================

{
    id: uuidv4(),
    question: "What is JDBC? Why is it used in Java applications?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of database connectivity in Java?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between Statement and PreparedStatement.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Why is file handling important in Java?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Name any four JDBC components.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Develop a Java application that connects to a database using JDBC. Perform INSERT, UPDATE, DELETE, and SELECT operations and explain the purpose of each JDBC component used in the program.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Write a Java program to read data from one file and write it into another file. Incorporate exception handling to ensure the program executes safely under different conditions.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},

// ====================== 2024 ======================

{
    id: uuidv4(),
    question: "What is the purpose of Servlets in Java web applications?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "List the stages of the Servlet life cycle.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between HttpServletRequest and HttpServletResponse.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of JavaBeans in web development?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Why is the MVC architecture used in web applications?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Develop a Java Servlet-based web application that processes client requests and generates dynamic responses. Explain the complete Servlet life cycle with the help of your implementation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Design a web application using the MVC architecture. Demonstrate how JavaBeans, Servlets, HttpServletRequest, and HttpServletResponse work together to process user requests and display dynamic content.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
// ====================== 2025 ======================

{
    id: uuidv4(),
    question: "What is the role of HTML in Java web applications?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "How does CSS improve the presentation of a web page?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of JavaScript in client-side web development?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Differentiate between client-side and server-side programming.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of the MVC design pattern in web application development?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "short",
    marks: 5,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Develop a complete Java-based web application using HTML, CSS, JavaScript, Servlets, JavaBeans, and JDBC. Explain how client-side and server-side components interact to process user requests and generate dynamic responses.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
{
    id: uuidv4(),
    question: "Design and implement a web-based Student Management System following the MVC architecture. Demonstrate user authentication, database connectivity, request processing, exception handling, and dynamic page generation using Java technologies.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "V",
    category: "long",
    marks: 10,
    course_code: "EC-331L",
    Subject: "Web Technologies Lab"
},
]

export {semesterFive}
