const semesterThree = [
    {
        "id": 1,
        "question": "Find domain and range of the function y = (x² + x − 2) / (x³ − x − x²)",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "MS-251 N",
        "Subject": "Calculus and Analytical Geometry",
        "category": "short",
        "marks": 5
    },
    {
        "id": 2,
        "question": "Evaluate the integral ∫ cos(2t) sin⁵(2t) dt",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "MS-251 N",
        "Subject": "Calculus and Analytical Geometry",
        "category": "short",
        "marks": 5
    },
    {
        "id": 3,
        "question": "Find parametric equations of the line through (2, −1, 5) that is parallel to ⟨−1, 2, 7⟩",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "MS-251 N",
        "Subject": "Calculus and Analytical Geometry",
        "category": "short",
        "marks": 5
    },
    {
        "id": 4,
        "question": "Find second order derivative of f(x) = (1 + 3x)⁸",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "MS-251 N",
        "Subject": "Calculus and Analytical Geometry",
        "category": "short",
        "marks": 5
    },
    {
        "id": 5,
        "question": "Show that y = cosx and y = sinx are the solutions to y'' + y = 0",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "MS-251 N",
        "Subject": "Calculus and Analytical Geometry",
        "category": "short",
        "marks": 5
    },
    {
        "id": 6,
        "question": "Find an equation of the plane through the points P₁(1,2,−1), P₂(2,3,1), and P₃(3,−1,2)",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "MS-251 N",
        "Subject": "Calculus and Analytical Geometry",
        "category": "short",
        "marks": 5
    },
    {
        "id": 7,
        "question": "Find the intervals on which g(x) = −x³ + 12x + 5, −3 ≤ x ≤ 3 is increasing and decreasing. Where does the function assume the extreme values and what are these values?",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "MS-251 N",
        "Subject": "Calculus and Analytical Geometry",
        "category": "long",
        "marks": 10
    },
    {
        "id": 8,
        "question": "Evaluate the integral ∫ r⁴(7 − r⁵/10)³ dr",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "MS-251 N",
        "Subject": "Calculus and Analytical Geometry",
        "category": "long",
        "marks": 10
    },
    {
        "id": 9,
        "question": "Evaluate the integral ∫₀^(π/2) (cosx + |cosx|) dx",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "MS-251 N",
        "Subject": "Calculus and Analytical Geometry",
        "category": "long",
        "marks": 10
    },
    {
        "id": 10,
        "question": "Find parametric equations for the line in which the planes 3x − 6y − 2z = 15 and 2x + y − 2z = 5 intersect",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "MS-251 N",
        "Subject": "Calculus and Analytical Geometry",
        "category": "long",
        "marks": 10
    }
,
  {
    "id": 1,
    "question": "Opportunity Cost.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 2,
    "question": "Economies of Scale.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 3,
    "question": "Perfect Competition.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 4,
    "question": "Cost Push Inflation.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 5,
    "question": "Cyclical Unemployment.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 6,
    "question": "Income Elasticity of Demand.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 7,
    "question": "Law of Supply.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 8,
    "question": "Intermediate things in GDP.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 9,
    "question": "Aggregate Demand and Aggregate Supply.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 10,
    "question": "Unemployment.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 11,
    "question": "Ceteris Paribus.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 12,
    "question": "Boom and Trough in Business Cycle.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 13,
    "question": "Variable Cost.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 14,
    "question": "Indifference Curve.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 15,
    "question": "Gross National Product.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "short",
    "marks": 2
  },
  {
    "id": 16,
    "question": "Define Monetary Policy and Fiscal Policy. Explain their objectives and tools to implement both policies (Hint: Discount rate and other tools for Monetary Policy & Taxes and other tools for Fiscal Policy).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "long",
    "marks": 15
  },
  {
    "id": 17,
    "question": "Use diagrams to illustrate how each event affects the equilibrium price and quantity of pizza: (A) Price of Mozzarella Cheese rises. (B) Health hazards of hamburgers are publicized affecting demand negatively. (C) Price of tomato sauce falls. (D) Consumers expect the price of pizza to fall next week. (E) Free home delivery offer affects demand positively.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "UE-171",
    "Subject": "Introduction to Economics",
    "category": "long",
    "marks": 15
  }
    ,
    {
        "id": 1,
        "question": "Differentiate microeconomics from macroeconomics.",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "UE-171",
        "Subject": "Introduction to Economics",
        "category": "short",
        "marks": 6
  },
    {
        "id": 2,
        "question": "Explain the cost of production as a factor of supply.",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "UE-171",
        "Subject": "Introduction to Economics",
        "category": "short",
        "marks": 6
  },
    {
        "id": 3,
        "question": "Define the Production Possibility Frontier with an example.",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "UE-171",
        "Subject": "Introduction to Economics",
        "category": "short",
        "marks": 6
  },
    {
        "id": 4,
        "question": "Discuss the Government Expenditures as a component of GDP.",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "UE-171",
        "Subject": "Introduction to Economics",
        "category": "short",
        "marks": 6
  },
    {
        "id": 5,
        "question": "Explain the relationship between interest rate and savings.",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "UE-171",
        "Subject": "Introduction to Economics",
        "category": "short",
        "marks": 6
  },
    {
        "id": 6,
        "question": "Describe the various forms of markets and compare their features.",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "UE-171",
        "Subject": "Introduction to Economics",
        "category": "long",
        "marks": 15
  },
    {
        "id": 7,
        "question": "Describe fiscal policy. Discuss its objectives and role in economic growth.",
        "index": true,
        "trim": true,
        "type": "past-paper",
        "year": 2023,
        "term": "Fall",
        "course_code": "UE-171",
        "Subject": "Introduction to Economics",
        "category": "long",
        "marks": 15
  }
,
  {
    "id": 1,
    "question": "A digital computer has a common bus system for 8 registers of 16 bit each. The bus is constructed using multiplexers. Keeping in view the given data answer the following: How many select inputs are there in each multiplexer? What is the size of multiplexers needed? How many multiplexers are there in the bus?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "Subject": "Computer Organization & Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Differentiate between horizontal and vertical microprogramming.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "Subject": "Computer Organization & Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "Design a 4-bit combinational incremental circuit using four full adder circuits.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "Subject": "Computer Organization & Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "Explain the working of a floating-point adder.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "Subject": "Computer Organization & Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "Explain how a DMA transfer is accomplished with the help of a neat diagram.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "Subject": "Computer Organization & Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "Define Linker and explain its role/need in computer systems organization.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "Subject": "Computer Organization & Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 7,
    "question": "Write an assembly program to sort a list of seven integers using bubble sort.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "Subject": "Computer Organization & Assembly Language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 8,
    "question": "How would you print capital 'P' with blue foreground and red background with no blinking property? Write its assembly code.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "Subject": "Computer Organization & Assembly Language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 9,
    "question": "Calculate the values of the following for the given instructions. You need to calculate the offset, opcode, PF, AF, ZF, AX, BX, IP.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "Subject": "Computer Organization & Assembly Language",
    "category": "long",
    "marks": 10
  }
    ,
{
    "id": 1,
    "question": "What is an object?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "Subject": "Object Oriented Programming",
    "category": "short",
    "marks": 6
},
{
    "id": 2,
    "question": "What is encapsulation and why is it important?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "Subject": "Object Oriented Programming",
    "category": "short",
    "marks": 6
},
{
    "id": 3,
    "question": "What is the purpose of constructors?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "Subject": "Object Oriented Programming",
    "category": "short",
    "marks": 6
},
{
    "id": 4,
    "question": "What is the 'this' pointer, and what does it refer to?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "Subject": "Object Oriented Programming",
    "category": "short",
    "marks": 6
},
{
    "id": 5,
    "question": "What is polymorphism and how is it achieved?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "Subject": "Object Oriented Programming",
    "category": "short",
    "marks": 6
},
{
    "id": 6,
    "question": "Write the implementation of a class named Algebra having two data members (a and b) of type integer with private access. Data members of this class should contain positive data and 0 (default value) for a particular object.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "Subject": "Object Oriented Programming",
    "category": "long",
    "marks": 10
},
{
    "id": 7,
    "question": "Write getter and setter methods.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "Subject": "Object Oriented Programming",
    "category": "long",
    "marks": 10
},
{
    "id": 8,
    "question": "Overload stream extraction operator for taking the inputs for a particular object's data from the user.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "Subject": "Object Oriented Programming",
    "category": "long",
    "marks": 10
},
{
    "id": 9,
    "question": "Write getDifferentObjects function which accepts an array of Algebra object with its size and return a newly created array having all those objects that are not-equal to the left-hand-side (calling) object. The function should also store the size of newly created array into a third parameter named newSize which is passed by reference to the function. The function should return NULL and store 0 in newSize if all the objects are equal to the left-hand-side (calling) object.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "Subject": "Object Oriented Programming",
    "category": "long",
    "marks": 10
}
,
  {
    "id": 1,
    "question": "What are the potential risks and consequences of not following ethical guidelines and professional codes of conduct in software engineering?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "Subject": "Professional Practice",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Discuss briefly the five functional units of a software engineering organization.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "Subject": "Professional Practice",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "With reference to the sources of funds, differentiate among 'grants', 'loans', and 'equity capital'.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "Subject": "Professional Practice",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "With reference to the contracts for the supply of custom-built software, list down some of the obligations of the client.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "Subject": "Professional Practice",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "What can be patented? And what is not patentable?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "Subject": "Professional Practice",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What do you understand by the term 'equal employment opportunity'? How can a software development firm ensure it?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "Subject": "Professional Practice",
    "category": "short",
    "marks": 5
  },
  {
    "id": 7,
    "question": "With reference to the intellectual property rights of computer software, write down some acts permitted in relation to copyright works. Give examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "Subject": "Professional Practice",
    "category": "long",
    "marks": 10
  },
  {
    "id": 8,
    "question": "List down the factors that impact the safety of a system. What measures can be taken to ensure the safety of a system throughout various stages of its development?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "Subject": "Professional Practice",
    "category": "long",
    "marks": 10
  },
  {
    "id": 9,
    "question": "With reference to finance and accounting of an organization, identify three annual statements and explain how each of them indicates the financial well-being of the organization.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "Subject": "Professional Practice",
    "category": "long",
    "marks": 10
  }
    ,
{
    "id": 1,
    "question": "How many times will the loop execute in the following code?\nMOV CH,0\nAA:\nMOV DL,'A'\nMOV AH,02\nINT 21H\nINC CH\nJNZ AA",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "CC-210N",
    "Subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
},
{
    "id": 2,
    "question": "Assume SI=0100, DI=0200 and Direction Flag is reset. What would be the contents of SI and DI after execution of instruction LODSB twice?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "CC-210N",
    "Subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
},
{
    "id": 3,
    "question": "Assume SP=0048. What would be the value of SP register after the execution of PUSH BX instruction twice?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "CC-210N",
    "Subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
},
{
    "id": 4,
    "question": "Assume DL contains the ASCII code of Upper case letter. Write instructions to convert it to lower case and print it. (Use some logic instruction for conversion)",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "CC-210N",
    "Subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
},
{
    "id": 5,
    "question": "How many times the loop will be executed in the following code?\nMOV CH,0\nAA:\nMOV DL,'A'\nMOV AH,02\nINT 21H\nDEC CH\nJNZ AA",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "CC-210N",
    "Subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
},
{
    "id": 6,
    "question": "A memory location has physical address 82AC4h that corresponds to offset address 1AC4h. Calculate the segment address and the maximum possible physical address in this segment.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "CC-210N",
    "Subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
},
{
    "id": 7,
    "question": "Write a program that will prompt the user to enter a string of decimal digits, ending with a carriage return and print the sum in hex on the next line. If the user enters an illegal character, he or she should be prompted to begin again.\nSample execution:\nEnter a decimal digits string: 1299843\nThe sum of the digits in hex is: 0024",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "CC-210N",
    "Subject": "Computer Organization and Assembly Language",
    "category": "long",
    "marks": 10
},
{
    "id": 8,
    "question": "Write down the note on DIV and MUL instruction, also explain all versions of these instruction with the help of examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "CC-210N",
    "Subject": "Computer Organization and Assembly Language",
    "category": "long",
    "marks": 10
},
{
    "id": 9,
    "question": "Read the following program and answer the question at end:\nMOV BX,247BH\nMOV CH,4\nAA:\nROL BX,4\nMOV DL,BL\nAND DL,0FH\nADD DL,30H\nCMP DL,3AH\nJL BB\nADD DL,07H\nBB:\nINT 21H\nDEC CH\nJNZ AA\n(i) What is the output of the program?\n(ii) What would be the value of DL register when 'AND DL,0FH' instruction is executed 2nd time in the loop?\n(iii) What would be the value of BX register when Program terminates?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "CC-210N",
    "Subject": "Computer Organization and Assembly Language",
    "category": "long",
    "marks": 10
}
    ,
{
    "id": 1,
    "question": "Explain the terms: 'Partnership' and 'Company'.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "CE-261",
    "Subject": "Professional Practices",
    "category": "short",
    "marks": 5
},
{
    "id": 2,
    "question": "Explain the meaning of the terms fixed assets and current assets. Give an example of each.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "CE-261",
    "Subject": "Professional Practices",
    "category": "short",
    "marks": 5
},
{
    "id": 3,
    "question": "Explain the purpose(s) of an appraisal system.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "CE-261",
    "Subject": "Professional Practices",
    "category": "short",
    "marks": 5
},
{
    "id": 4,
    "question": "Differentiate between two organization structures: structure by market sector and structure by technology.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "CE-261",
    "Subject": "Professional Practices",
    "category": "short",
    "marks": 5
},
{
    "id": 5,
    "question": "What is informed consent? Explain how informed consent helps protect the individual privacy of Internet users.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "CE-261",
    "Subject": "Professional Practices",
    "category": "short",
    "marks": 5
},
{
    "id": 6,
    "question": "One of the important sections of the Software Engineering Code of Ethics is 'The Public Interest'. How can computing professionals protect the public interest?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "CE-261",
    "Subject": "Professional Practices",
    "category": "short",
    "marks": 5
},
{
    "id": 7,
    "question": "Discuss the key elements that should be included in a contract for the supply of custom-built software.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "CE-261",
    "Subject": "Professional Practices",
    "category": "long",
    "marks": 10
},
{
    "id": 8,
    "question": "What is 'Computer Misuse'? Highlight some of the categories of misuse of computers. Give examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "CE-261",
    "Subject": "Professional Practices",
    "category": "long",
    "marks": 10
},
{
    "id": 9,
    "question": "Define human resource management (HRM) and explain its functions for a software engineering organization.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "CE-261",
    "Subject": "Professional Practices",
    "category": "long",
    "marks": 10
},
    {
        "id": 1,
        "question": "How can you identify objects in problem domain description?",
        "index": 1,
        "trim": "short",
        "type": "theory",
        "year": 2024,
        "term": "Spring",
        "course_code": "CC-211",
        "Subject": "Object Oriented Programming",
        "category": "Q1",
        "marks": 6
    },
    {
        "id": 2,
        "question": "How is data hiding achieved in object-oriented programming?",
        "index": 2,
        "trim": "short",
        "type": "theory",
        "year": 2024,
        "term": "Spring",
        "course_code": "CC-211",
        "Subject": "Object Oriented Programming",
        "category": "Q1",
        "marks": 6
    },
    {
        "id": 3,
        "question": "Can constructor be overloaded in? If so, how?",
        "index": 3,
        "trim": "short",
        "type": "theory",
        "year": 2024,
        "term": "Spring",
        "course_code": "CC-211",
        "Subject": "Object Oriented Programming",
        "category": "Q1",
        "marks": 6
    },
    {
        "id": 4,
        "question": "What are static member functions? Are they of any use?",
        "index": 4,
        "trim": "short",
        "type": "theory",
        "year": 2024,
        "term": "Spring",
        "course_code": "CC-211",
        "Subject": "Object Oriented Programming",
        "category": "Q1",
        "marks": 6
    },
    {
        "id": 5,
        "question": "What is pure virtual function and what purpose it serves?",
        "index": 5,
        "trim": "short",
        "type": "theory",
        "year": 2024,
        "term": "Spring",
        "course_code": "CC-211",
        "Subject": "Object Oriented Programming",
        "category": "Q1",
        "marks": 6
    },
    {
        "id": 6,
        "question": "Write the implementation of a class named Binary having two data x and y of type integer with private access. Data member of this class should contain 1 and 0 (default value for a particular object). Write default and parameterized constructor.",
        "index": 1,
        "trim": "long",
        "type": "coding",
        "year": 2024,
        "term": "Spring",
        "course_code": "CC-211",
        "Subject": "Object Oriented Programming",
        "category": "Q2",
        "marks": 10
    },
    {
        "id": 7,
        "question": "Write a standard implementation of overloaded arithmetic assignment operator ‘+=’.",
        "index": 2,
        "trim": "long",
        "type": "coding",
        "year": 2024,
        "term": "Spring",
        "course_code": "CC-211",
        "Subject": "Object Oriented Programming",
        "category": "Q2",
        "marks": 10
    },
    {
        "id": 8,
        "question": "Write getEqualBinary function which accepts an array of Binary objects with its size and returns a newly created array having all those objects that are equal to the left-hand-side (calling) object. The function should also store the size of newly created array into a third parameter passed by reference to the function. The function should return NULL and store 0 in newSize, if all the objects are different from the left-hand-side (calling) object.",
        "index": 3,
        "trim": "long",
        "type": "coding",
        "year": 2024,
        "term": "Spring",
        "course_code": "CC-211",
        "Subject": "Object Oriented Programming",
        "category": "Q2",
        "marks": 10
    }
]
export {semesterThree}