const shortQuestion = [
  {
    "id": 1,
    "question": "Solve the recurrence equation T(n) = 2T(n/2) + n^2.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Illustrate the operation of insertion sort on the array A = [13,8,29,3,22,5]. Show the contents of the array after each step.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "Write an algorithm that determines whether the input list contains a duplicate element.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "Briefly explain divide and conquer algorithm with the help of a suitable example.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "Using matrix-chain multiplication, find out different costs of multiplying three matrices A (20x50), B (50x10), and C (10x30).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What is the difference between P and NP problems?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 7,
    "question": "Write an algorithm to determine whether or not a list of n elements is sorted.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 4
  },
  {
    "id": 8,
    "question": "Write an algorithm to split a list into p < n sublists of same size k, with an exception of the last list. Example: if input list is [2,5,3,6,4] and k = 2, then output should be [2,5], [3,6], and [4].",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 6
  },
  {
    "id": 9,
    "question": "Find the minimum spanning tree of the graph using Kruskal’s algorithm. Show the order in which edges were added.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 4
  },
  {
    "id": 10,
    "question": "Find the shortest path from vertex a to vertex i of the graph using Dijkstra’s algorithm.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 6
  },
  {
    "id": 11,
    "question": "What is hashing and hashing functions?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 4
  },
  {
    "id": 12,
    "question": "Write an algorithm to implement two stacks in a single array of size n such that overflow is avoided when one stack has free space in the other.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 6
  }
]