const shortQuestion = [
  {
    "id": 1,
    "question": "Solve the recurrence equation T(n) = 2T(n/2) + n^2.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Illustrate the operation of insertion sort on the array A = [13,8,29,3,22,5]. Show the contents of the array after each step.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "Write an algorithm that determines whether the input list contains a duplicate element.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "Briefly explain divide and conquer algorithm with the help of a suitable example.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "Using matrix-chain multiplication, find out different costs of multiplying three matrices A (20x50), B (50x10), and C (10x30).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What is the difference between P and NP problems?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "short",
    "marks": 5
  },
  {
    "id": 7,
    "question": "Write an algorithm to determine whether or not a list of n elements is sorted.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 4
  },
  {
    "id": 8,
    "question": "Write an algorithm to split a list into p < n sublists of same size k, with an exception of the last list. Example: if input list is [2,5,3,6,4] and k = 2, then output should be [2,5], [3,6], and [4].",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 6
  },
  {
    "id": 9,
    "question": "Find the minimum spanning tree of the graph using Kruskal’s algorithm. Show the order in which edges were added.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 4
  },
  {
    "id": 10,
    "question": "Find the shortest path from vertex a to vertex i of the graph using Dijkstra’s algorithm.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 6
  },
  {
    "id": 11,
    "question": "What is hashing and hashing functions?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 4
  },
  {
    "id": 12,
    "question": "Write an algorithm to implement two stacks in a single array of size n such that overflow is avoided when one stack has free space in the other.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "DC-321",
    "subject": "Design and Analysis of Algorithms",
    "category": "long",
    "marks": 6
  },
  {
    "id": 1,
    "question": "A digital computer has a common bus system for 8 registers of 16 bit each. The bus is constructed using multiplexers. How many select input are there in each multiplexer? What is the size of multiplexers needed? How many multiplexers are there in the bus?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Differentiate between horizontal and vertical microprogramming.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "Design a 4-bit combinational incremental circuit using four full adder circuits.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "Explain the working of a floating-point adder.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "Explain how a DMA transfer is accomplished with the help of a neat diagram.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "Define Linker and explain its role/need in computer system organization.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "subject": "Computer Organization and Assembly Language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 7,
    "question": "Write an assembly program to sort a list of seven integers using bubble sort.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "subject": "Computer Organization and Assembly Language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 8,
    "question": "How would you print capital 'P' with blue foreground and red background with no blinking property? Write its assembly code.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "subject": "Computer Organization and Assembly Language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 9,
    "question": "Calculate the values of offset, opcode, AX, BX, IP, PF, AF, ZF for the given instructions: [org 0x0100], mov ax,4; mov bx,2; add ax,bx; mov bx,24; add ax,bx.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "DC-221",
    "subject": "Computer Organization and Assembly Language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 1,
    "question": "What is an object?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "subject": "Object Oriented Programming",
    "category": "short",
    "marks": 6
  },
  {
    "id": 2,
    "question": "What is encapsulation and why is it important?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "subject": "Object Oriented Programming",
    "category": "short",
    "marks": 6
  },
  {
    "id": 3,
    "question": "What is the purpose of constructors?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "subject": "Object Oriented Programming",
    "category": "short",
    "marks": 6
  },
  {
    "id": 4,
    "question": "What is the 'this' pointer, and what does it refer to?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "subject": "Object Oriented Programming",
    "category": "short",
    "marks": 6
  },
  {
    "id": 5,
    "question": "What is polymorphism and how is it achieved?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "subject": "Object Oriented Programming",
    "category": "short",
    "marks": 6
  },
  {
    "id": 6,
    "question": "Write getter and setter methods for a class Algebra having two private integer data members a and b.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "subject": "Object Oriented Programming",
    "category": "long",
    "marks": 10
  },
  {
    "id": 7,
    "question": "Overload stream extraction operator for taking inputs for a particular object's data from the user.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "subject": "Object Oriented Programming",
    "category": "long",
    "marks": 10
  },
  {
    "id": 8,
    "question": "Write getDifferentObjects function which accepts an array of Algebra objects with its size and returns a new array having all objects that are not equal to the calling object. Also store size in newSize and return NULL if none found.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-211",
    "subject": "Object Oriented Programming",
    "category": "long",
    "marks": 10
  },
  {
    "id": 1,
    "question": "[Please insert exact question text about Software engineering ethics]",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "subject": "Professional Practices",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "[Please insert exact question text about Functional units]",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "subject": "Professional Practices",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "[Please insert exact question text about Funding distinctions]",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "subject": "Professional Practices",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "[Please insert exact question text about Patentability]",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "subject": "Professional Practices",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "[Please insert exact question text about Intellectual property rights]",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "subject": "Professional Practices",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "[Please insert exact question text about System safety measures]",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "subject": "Professional Practices",
    "category": "long",
    "marks": 15
  },
  {
    "id": 7,
    "question": "[Please insert exact question text about Financial statements]",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-261",
    "subject": "Professional Practices",
    "category": "long",
    "marks": 15
  }
]


export {}