const semesterEight = [
  {
    "id": 1,
    "question": "Define mean. Also write its formula.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Define management and list its four basic functions.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "Describe three important roles of a manager (Mintzberg's categories).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "What is organizational culture? Give two characteristics.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "Distinguish between external and internal environment with one example each.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What is strategic planning? How does it differ from operational planning?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  },
  {
    "id": 7,
    "question": "Define bounded rationality in decision making.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Explain \"Managing and the Manager's Job.\" Discuss the major managerial skills and how they are applied at different managerial levels.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Examine the ways in which an organization's external environment influences managerial decisions. Use examples to support your answer.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Discuss the planning process in detail. Compare levels of planning (strategic, tactical, operational) and their significance for an organisation.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "Define organizational environment and list two components of the external environment.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "What are organizational values? Give one example of how values influence behavior.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "Name two rational perspectives on decision making.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "What is group decision making? Give one advantage and one drawback.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "Define delegation and list its three key elements.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What are the main forces for change in organisations?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Analyze the behavioral aspects of decision making. Compare rational decision making with behavioral decision making and show why managers must understand both.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Discuss the steps in the change process and outline strategies for overcoming resistance to change. Give relevant examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Explain different approaches to leadership (e.g., trait, behavioral, contingency). Which approach is most useful during organisational change? Justify.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "What is organizational structure? Mention two common types.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-472",
    "Subject": "principles of management ",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Define span of control. How does it affect structure?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-472",
    "Subject": "principles of management ",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "What do you understand by organizational goals? Give an example of a well-stated goal.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-472",
    "Subject": "principles of management ",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "Briefly explain the innovation process.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-472",
    "Subject": "principles of management ",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "What is a decision tree conceptually? When would a manager use it?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-472",
    "Subject": "principles of management ",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "Define political behavior in organizations. Give one example.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-472",
    "Subject": "principles of management ",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Describe the organizing process in an organization that is expanding rapidly. Discuss the pros and cons of centralization vs. decentralization in that context.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Explain group and team decision making in organizations. Evaluate techniques (brainstorming, nominal group technique, Delphi, etc.) and recommend when each should be used.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Discuss managing change and innovation in organizations. Explain steps managers should take to build and sustain an innovative culture.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-472",
    "Subject": "principles of management",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "عزف الحروف المنفصلة مع مثالين۔",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "ما الفرق بين الاسم والفعل؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "عزف الفعل الماضي مع مثال.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "ما هو الجمع؟ اذكر أنواعه.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "ما المقصود بالمذكر والمؤنث؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "عزف الجملة الاسمية.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 7,
    "question": "ما هي الضمائر المتصلة؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 8,
    "question": "عزف المخارج مع مثال واحد.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "شرح مفصل عن الفعل الماضي، الفعل المضارع، وفعل الأمر مع أمثلة.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "وضح الجملة الاسمية والجملة الفعلية مع الإعراب.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "اشرح قواعد الإملاء مع أمثلة مناسبة.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 4,
    "question": "ترجم الفقرة التالية إلى العربية أو الأردو حسب المعنى.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 5,
    "question": "اكتب ملاحظات تفصيلية عن حروف الهجاء ومخارجها.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "ما هو المركب الإضافي؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "عزف المركب التوصيفي.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "ما المقصود بالاسم المفرد؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "ما هو الفعل الصحيح؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "عزف الفعل المعتل.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "ما معنى الجمع السالم؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 7,
    "question": "اذكر أنواع الضمائر.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 8,
    "question": "ما هي علامات الاسم؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "شرح المركب الإضافي والمركب التوصيفي مع مثال.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "بين أنواع الأسماء (مفرد، مثنى، جمع) بالتفصيل.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "ناقش الفعل الصحيح والفعل المعتل مع أمثلة.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 4,
    "question": "اشرح قواعد الإعراب الأساسي.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 5,
    "question": "ترجم فقرة قصيرة مع الشرح النحوي.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "ما هو الفعل المضارع؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "عزف الجملة الفعلية.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "ما المقصود بالجمع المكسر؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "ما هي حروف الجر؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "عزف الضمائر المنفصلة.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "ما الفرق بين الفعل اللازم والمتعدي؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 7,
    "question": "ما هي علامات الفعل؟",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 8,
    "question": "عزف القواعد الإملائية.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "شرح مفصل عن الجمع السالم والجمع المكسر مع أمثلة.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "ناقش الضمائر المنفصلة والمتصلة مع استعمالها.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "اشرح حروف الجر واستخداماتها مع الإعراب.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 4,
    "question": "بين أنواع الجمل في اللغة العربية.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 5,
    "question": "اكتب ملاحظات عن أهمية تعلم اللغة العربية.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-471",
    "Subject": "Arabic language",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "Define information security and state its primary objectives.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "What is the CIA triad?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "Differentiate between symmetric and asymmetric cryptography.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "What is a hash function? Mention one application.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "Define authentication and authorization.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What is malware? Name any two types.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Explain information securityfoundations and discuss major security design principles with examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Describe symmetric and asymmetric cryptographic systems. Compare their advantages and limitations.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Discuss authentication mechanisms and access control models used in modern systems.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "What is encryption?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Define digital signature.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "What is key management?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "What are software vulnerabilities?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "Define intrusion detection system (IDS).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What is database security?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Explain encryption techniques, digital signatures, and their role in ensuring confidentiality and integrity.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Discuss software security, common vulnerabilities, and protection mechanisms.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Explain network security architecture, including firewalls and intrusion detection systems.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "What is access control?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Define discretionary access control (DAC).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "What is malware propagation?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "Define privacy in information systems.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "What is anonymization of data?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What is a security mechanism?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Explain access control models (DAC, MAC, RBAC) with suitable examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Discuss malware analysis, detection techniques, and prevention strategies.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Explain database security threats and countermeasures.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "CC-413",
    "Subject": "information security",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "Define social work and state two objectives of social services.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "What is meant by the philosophical base of social service? Give one example.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "Explain briefly the Islamic concept of social welfare.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "Name three primary methods of social work practice.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "List three important fields of social practice in Pakistan.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "Define NGO and give one example of a national NGO.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Discuss the scope and generic principles of social services. Explain how these principles guide practice in health and education sectors.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Describe primary and secondary methods of social work (casework, group work, community organization, etc.) and give examples of their application.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Analyze major social problems (poverty, child labour, unemployment) in Pakistan, including their causes, social impact, and practical interventions.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "Define social institution and give two examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "What is overpopulation and mention one of its social consequences?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "Define social exclusion or minority marginalization.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "What is rehabilitation in social work?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "Mention two functions of the World Health Organization (WHO) relevant to social services.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What is community participation?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Explain the structure and types of social institutions (family, religious, educational, political) and their role in social welfare.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Discuss poverty and inequality as social problems. Explain their measurement, root causes, and describe three strategies to reduce poverty.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Examine social welfare in Pakistan by discussing major welfare initiatives for children, women, and senior citizens. Evaluate their strengths and weaknesses.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "What do you understand by professional versus voluntary social services?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Define child labour and name one protective law or program (describe in general).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "What is social rehabilitation?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "Define corruption as a social problem and mention one social consequence.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "Name two regional support programs (such as NRSP and AKRSP) and mention one service they provide.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What is ICT for social work? (One line)",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Critically examine professional and voluntary roles in social services and explain how coordination between them can be improved.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Discuss national social welfare organizations and schemes (NRSP, PRSP, BRSP, Orangi Pilot Project), focusing on their objectives and impact on local communities.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Describe major social problems such as addiction and gender-based violence, highlighting prevention and rehabilitation strategies.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "UE-473",
    "Subject": "social services",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "Define programming language and explain its role in software development.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "What is meant by models of computation?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "Define syntax and semantics.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "What is a context-free grammar (CFG)?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "What is static semantics?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "Define regular expressions.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Explain language design principles and discuss the trade-offs involved in language design.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "SC-342",
    "Subject": "theory of programming language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Describe syntax and semantics in detail. Explain context-free grammars (CFGs) and Backus–Naur Form (BNF) with examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "SC-342",
    "Subject": "theory of programming language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Discuss algebraic, axiomatic, and denotational semantics. Compare their purposes and uses.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "CourseCode": "SC-342",
    "Subject": "theory of programming language",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "What is BNF grammar?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Define attribute grammar.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "What is pragmatics in programming languages?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "What is operational equivalence?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "Define functional programming.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What is lambda calculus?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Explain syntax analysis techniques including regular expressions and context-free grammars.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Discuss attribute grammars and static semantics with suitable examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Explain the functional programming paradigm and its advantages over imperative programming.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "long",
    "marks": 10
  }
,
  {
    "id": 1,
    "question": "What is a formal language?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 2,
    "question": "Define expressions in programming languages.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 3,
    "question": "What is denotational semantics?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 4,
    "question": "Define axiomatic semantics.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 5,
    "question": "What is logic programming?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  },
  {
    "id": 6,
    "question": "What is an inference engine?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "short",
    "marks": 5
  }
,
  {
    "id": 1,
    "question": "Explain different models of computation and their relevance to modern programming languages.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 2,
    "question": "Compare operational, axiomatic, and denotational semantics in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "long",
    "marks": 10
  },
  {
    "id": 3,
    "question": "Discuss logic programming, its characteristics, and applications.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "CourseCode": "SC-341",
    "Subject": "theory of programming language",
    "category": "long",
    "marks": 10
  }
]

export {semesterEight}