import { v4 as uuidv4 } from "uuid";
const semesterSix = [

// ====================== 2021 ======================

{
    id: uuidv4(),
    question: "What is a computer network? State any four advantages of networking.",
    index: true,
    trim: true,  
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Differentiate between LAN, MAN, and WAN.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What is network topology? Name any four network topologies.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Why is layered architecture used in computer networks?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Differentiate between circuit switching and packet switching.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Explain the layered architecture of computer networks. Discuss the functions of each layer and describe how data is transmitted from the sender to the receiver through the networking stack.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Compare circuit switching and packet switching in detail. Discuss their working principles, advantages, limitations, and suitable real-world applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313",
    Subject: "Computer Networks"
},

// ====================== 2022 ======================

{
    id: uuidv4(),
    question: "State the primary responsibilities of the Physical Layer.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What are the functions of the Data Link Layer?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What is MAC addressing? Why is it required?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Differentiate between hub, switch, and router.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What are multiple access techniques? Mention any two examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Explain the functionality of the Physical Layer and Data Link Layer. Discuss framing, error detection, media access control, and multiple access techniques with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Describe the architecture of a Local Area Network (LAN). Explain the role of networking devices, MAC addressing, and different LAN technologies in establishing reliable communication.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
// ====================== 2023 ======================

{
    id: uuidv4(),
    question: "Differentiate between IPv4 and IPv6.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What is IP addressing? Why is it important?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What is subnetting? State its advantages.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What is CIDR? Why is it used in modern networks?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What is the purpose of routing protocols?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Explain IPv4 and IPv6 addressing schemes in detail. Compare their addressing structure, header format, advantages, limitations, and practical applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Discuss IP addressing, subnetting, CIDR, and routing protocols. Illustrate subnet calculation with suitable examples and explain how routers determine the best path for packet delivery.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313",
    Subject: "Computer Networks"
},

// ====================== 2024 ======================

{
    id: uuidv4(),
    question: "Differentiate between TCP and UDP.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What are ports and sockets?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What is flow control in computer networks?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What is congestion control? Why is it necessary?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What is connection establishment in TCP?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Compare TCP and UDP transport protocols. Explain their features, connection establishment process, reliability, flow control, congestion control, and practical applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Explain the Transport Layer in detail. Discuss ports, sockets, connection establishment, flow control, and congestion control with the help of suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313",
    Subject: "Computer Networks"
},{
    id: uuidv4(),
    question: "Explain the importance of computer networks and discuss different network architectures.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Define IPv4 addressing and explain different classes of IP addresses.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Explain the purpose of routing protocols in computer networks.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "What are application layer protocols? Explain their functions.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Explain the role of networking devices in data communication.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Explain the transport layer protocols and describe the process of connection establishment.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{
    id: uuidv4(),
    question: "Discuss the latest trends in computer networks and explain their impact on modern communication.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313",
    Subject: "Computer Networks"
},
{


    id: uuidv4(),
    question: "Explain different types of network components and their functions.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Define physical and logical topologies with examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain guided and unguided transmission media.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "What is IP addressing? Explain private and loopback addresses.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the purpose of ping command in network troubleshooting.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the procedure for setting up a Local Area Network using Ethernet cables and IP configuration.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Describe the installation and configuration of Active Directory on a Domain Controller.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain different types of network connections and transmission modes.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "What are T568-A and T568-B standards used for?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain subnetting and supernetting in IP addressing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Define network devices such as hub, switch and router.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the use of ipconfig and ifconfig commands.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the configuration of DNS server and different types of DNS zones.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Describe installation and configuration of Linux OS, file systems and user permissions.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},{
    id: uuidv4(),
    question: "Explain different types of network addressing and differentiate between physical and logical addresses.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "What are the different types of network cables used in LAN setup?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the function of ARP and RARP protocols.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "What is VLAN? Explain its basic concept.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the purpose of network commands such as ping and traceroute.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the installation and configuration of a file server and quota server.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Describe the configuration of DHCP, DNS and NAT servers in a network environment.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain different networking devices used in computer networks.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "What is the purpose of wireless access points in networking?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain TCP and UDP protocols with their applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "What is the use of Netstat and Nslookup commands?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the concept of router configuration in computer networks.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the installation and configuration of wireless router and Cisco switches.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Describe WAN simulation setup and implementation of static and dynamic routing protocols.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},{
    id: uuidv4(),
    question: "Explain the concept of network simulation and its importance in computer networks.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "What are the basic commands used for network troubleshooting?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the difference between manageable and non-manageable switches.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "What is a Domain Controller and why is it used?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the purpose of ACL configuration on routers.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Explain the complete procedure for setting up WAN using network simulator and configuring routers to connect multiple LANs.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},
{
    id: uuidv4(),
    question: "Describe the implementation of RIP, IGRP and ACLs configuration on routers.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "CC-313L",
    Subject: "Computer Networks Lab"
},{
    id: uuidv4(),
    question: "Define parallel computing and explain its importance in modern computing systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain the difference between synchronous and asynchronous computation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "What is distributed computing? Explain its basic characteristics.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain MIMD and SIMD architectures.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Define load balancing and explain its role in distributed systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain parallel architectures and discuss different parallel programming models.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Discuss fault tolerance techniques and synchronization mechanisms in distributed systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain the concept of concurrency and concurrency control.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "What are interconnection topologies? Explain their importance.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain the concept of memory consistency model.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "What is Message Passing Interface (MPI)?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain the purpose of multithreaded programming.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain GPU architecture and discuss GPU programming techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Discuss parallel algorithms and performance analysis techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain the difference between parallel computing and distributed computing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "What are memory hierarchies? Explain their importance in parallel systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Define scalability and explain its importance in distributed computing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain shared memory and distributed memory programming models.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "What is synchronization? Explain its role in parallel programs.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain different programming models used in parallel and distributed computing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Discuss load balancing techniques and scheduling strategies in distributed systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain fault tolerance and its importance in distributed systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "What are parallel I/O operations? Explain their purpose.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain the concept of heterogeneous computing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Define message passing and explain MPI communication.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain the role of cloud computing platforms in distributed computing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain performance analysis and tuning techniques for parallel applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Discuss distributed storage systems and their role in large-scale computing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},{
    id: uuidv4(),
    question: "Explain GPU architecture and its role in parallel computing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "What are parallel algorithms? Explain their importance.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain the concept of process scheduling in distributed systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Define OpenMP and explain its use in parallel programming.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain the role of Hadoop in distributed computing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Discuss different parallel architectures and explain their performance evaluation techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},
{
    id: uuidv4(),
    question: "Explain cloud and distributed computing tools including AWS, OpenStack, and Globus.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-323",
    Subject: "Parallel & Distributed Computing"
},{
    id: uuidv4(),
    question: "Explain the history of Microsoft technologies and introduction to .NET framework.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Define CLR, CLS and CTS in .NET architecture.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain managed and unmanaged code in .NET framework.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "What is C#? Explain boxing and unboxing concepts.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain JavaScript data types, variables and functions.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain multi-tier architecture and discuss its implementation in enterprise applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain ADO.NET architecture and discuss disconnected model with DataSet and DataAdapter.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "What is MSIL and explain its role in .NET framework.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain .NET assemblies and their types.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Define delegates and explain multicast delegates.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain Browser Object Model (BOM) and Document Object Model (DOM).",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "What are LINQ queries? Explain basic operations of LINQ.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain Entity Framework architecture and discuss Entity Data Model components.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain ASP.NET MVC architecture, controllers, action methods and routing mechanism.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},{
    id: uuidv4(),
    question: "Explain the concept of SQL Injection and parameterized queries in ADO.NET.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "What are Windows Forms? Explain their use in application development.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain jQuery effects and their applications in web development.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Differentiate between eager loading and lazy loading in Entity Framework.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain Razor syntax and code expressions in ASP.NET MVC.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain ASP.NET MVC application structure and discuss controllers and action methods.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Discuss service-oriented architecture and explain SOAP, WSDL and service contracts.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain C# fundamentals and object-oriented programming concepts.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "What are data annotations in ASP.NET MVC?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain client-side and server-side validation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Define RESTful services and explain CRUD operations.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "What is Web API? Explain its purpose in enterprise applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain WCF architecture and discuss ABC (Address, Binding, Contract) of WCF.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain MVC security, authentication, authorization and membership features.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},{
    id: uuidv4(),
    question: "Explain the architecture of .NET framework and its main components.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "What is LINQ? Explain LINQ to Objects and LINQ to SQL.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain POCO classes and DBContext API in Entity Framework.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain XML and JSON data formats used in web services.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "What are MVC model binding and model state validation?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain ADO.NET Entity Framework and describe querying of entity data models.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},
{
    id: uuidv4(),
    question: "Explain RESTful services, Web API and consuming CRUD operations using jQuery AJAX and JSON.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-332",
    Subject: "Enterprise Application Development"
},{
    id: uuidv4(),
    question: "Explain mobile application development platforms and their importance.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Describe Android operating system architecture.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "What are fragments in Android application development?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain intents and their use in Android applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain the purpose of notifications in mobile applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain Android architecture and discuss different components of an Android application.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Discuss user interface design, views and screen orientation handling in Android applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain HTML5 features used for mobile application development.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Compare Android and iOS mobile platforms.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "What are views in Android? Explain different types of views.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain user preferences and data persistence in mobile applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain the process of sending SMS and emails through mobile applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain mobile application development lifecycle and deployment process on app stores.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Discuss mobile programming languages and challenges related to mobility and wireless communication.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},{
    id: uuidv4(),
    question: "Explain the architecture and framework of iOS mobile operating system.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "What is the role of Eclipse in Android application development?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain the concept of adapting display orientation in mobile applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "What are action bars in Android applications? Explain their purpose.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain location-aware applications and their uses.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain data storage, sharing and persistence techniques in mobile applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Discuss web services access in mobile applications using HTTP and explain consuming web services.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain Windows Mobile platform and its application development environment.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "What are the major components of an Android application screen?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain threading in mobile application development.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain the process of publishing Android applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "What are mobile platform constraints?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain user interface creation and handling UI events in Android applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Discuss performance and power tradeoffs in mobile application development.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},{
    id: uuidv4(),
    question: "Explain Android application framework and its major components.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain the use of built-in applications using intents in Android.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "What are mobile web services? Explain their importance.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain emerging technologies in mobile application development.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain challenges associated with wireless communication and mobile computing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Explain the complete Android application development process from design to deployment.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Discuss location-aware applications, performance optimization and power management techniques in mobile applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "EC-333",
    Subject: "Mobile Application Development"
},
{
    id: uuidv4(),
    question: "Define Artificial Intelligence and explain its basic components.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain different branches of Artificial Intelligence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "What is knowledge representation? Explain its importance in AI.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain propositional logic in Artificial Intelligence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Differentiate between supervised and unsupervised learning.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain problem solving by searching and discuss informed and uninformed search techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Discuss reasoning and knowledge representation techniques used in Artificial Intelligence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain First Order Logic and its applications in AI.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "What are constraint satisfaction problems?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain local search algorithms.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "What is machine learning? Explain its types.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain reinforcement learning in Artificial Intelligence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain adversarial search and discuss Min-Max algorithm with Alpha-Beta pruning.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Discuss uncertainty handling in AI and explain fuzzy logic.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},{
    id: uuidv4(),
    question: "Explain the process of identifying AI systems and their characteristics.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Differentiate between informed and uninformed search techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain game playing in Artificial Intelligence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "What is fuzzy logic? Explain its role in AI systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain recent trends and applications of Artificial Intelligence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Discuss constraint satisfaction problems and their solving techniques in AI.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain learning techniques in AI including supervised, unsupervised and reinforcement learning.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain the basic concepts and goals of Artificial Intelligence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "What is reasoning in AI? Explain its types.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain alpha-beta pruning algorithm.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain knowledge representation using logic.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Describe uncertainty in Artificial Intelligence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain adversarial search techniques and discuss Min-Max algorithm in detail.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Discuss AI applications and analyze different AI-based systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain the basic components and applications of Artificial Intelligence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain propositional logic and First Order Logic in AI.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "What are searching techniques in AI? Explain local search briefly.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain supervised learning and unsupervised learning.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "What are recent trends in Artificial Intelligence?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Explain problem solving by searching methods and compare informed and uninformed search algorithms.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},
{
    id: uuidv4(),
    question: "Discuss uncertainty handling in AI and explain fuzzy logic with applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324",
    Subject: "Artificial Intelligence"
},{
    id: uuidv4(),
    question: "Implement propositional logic using Artificial Intelligence techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain the implementation of First Order Logic in AI systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Implement uninformed search algorithms in Artificial Intelligence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain the implementation of constraint satisfaction problems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Implement supervised and unsupervised learning techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain the implementation of informed and local search algorithms with examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Implement adversarial search using Min-Max algorithm and Alpha-Beta pruning.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2021,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain knowledge representation implementation in AI.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "What are informed searching techniques? Explain their implementation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain local search algorithms with practical examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain game playing techniques used in AI.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain reinforcement learning implementation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Discuss implementation of search algorithms for solving AI problems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain uncertainty handling techniques and implementation of fuzzy logic.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},{
    id: uuidv4(),
    question: "Implement propositional logic and explain its use in knowledge representation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain the implementation of First Order Logic using AI programming techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Implement breadth first search and depth first search algorithms.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain constraint satisfaction problems with implementation examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Implement fuzzy logic for handling uncertainty in AI systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain the implementation of Min-Max algorithm and Alpha-Beta pruning for game playing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Discuss implementation techniques of machine learning algorithms including supervised and unsupervised learning.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain AI problem solving techniques and their implementation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "What are search strategies in AI? Explain their implementation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain local search implementation techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain adversarial search and its implementation in AI games.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain reinforcement learning and its practical implementation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain implementation of knowledge representation and reasoning techniques in AI.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Discuss implementation of learning algorithms and uncertainty handling methods in AI applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},{
    id: uuidv4(),
    question: "Implement reasoning and knowledge representation techniques in Artificial Intelligence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain the implementation of propositional logic in AI applications.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Implement informed and uninformed search algorithms.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain the implementation of constraint satisfaction problems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Explain the implementation of fuzzy logic for uncertainty handling.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "short",
    marks: 5,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Implement adversarial search using Min-Max algorithm and Alpha-Beta pruning with suitable examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
},
{
    id: uuidv4(),
    question: "Discuss implementation of supervised, unsupervised and reinforcement learning algorithms in AI systems.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2025,
    semester: "VI",
    category: "long",
    marks: 10,
    course_code: "DC-324L",
    Subject: "Artificial Intelligence Lab"
}
]

export {semesterSix}