export const semesterFour = [
  {
    "id": 1,
    "question": "Differentiate between Psychologist and Psychiatrist.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 2,
    "question": "Define Attention.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 3,
    "question": "Differentiate between STM and LTM.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 4,
    "question": "What is Artificial Intelligence?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 5,
    "question": "Define Social Cognition.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 6,
    "question": "Discuss Psychodynamic Theory and explain Id, Ego and Superego.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 7,
    "question": "Explain Nervous System and its major parts.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  }
,
  {
    "id": 1,
    "question": "Define Psychology.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 2,
    "question": "What is Clinical Psychology?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 3,
    "question": "Define Forgetting.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 4,
    "question": "What is Sensation?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 5,
    "question": "Define Dream.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 6,
    "question": "Discuss different schools of thought in Psychology.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 7,
    "question": "Explain Intelligence and Intelligence Testing.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  }
,
  {
    "id": 1,
    "question": "Define Psychology.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 2,
    "question": "What is Clinical Psychology?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 3,
    "question": "Define Forgetting.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 4,
    "question": "What is Sensation?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 5,
    "question": "Define Dream.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 6,
    "question": "Discuss different schools of thought in Psychology.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 7,
    "question": "Explain Intelligence and Intelligence Testing.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  }
,
  {
    "id": 1,
    "question": "What is Observational Method?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 2,
    "question": "Define Child Psychology.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 3,
    "question": "What is Conscious Mind?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 4,
    "question": "Define Personality.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 5,
    "question": "What is Impression Formation?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 6,
    "question": "Explain Perception and its characteristics.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 7,
    "question": "Discuss Learning and its methods.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  }
,
  {
    "id": 1,
    "question": "Define Clinical Method.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 2,
    "question": "What is Applied Psychology?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 3,
    "question": "Define Subconscious Mind.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 4,
    "question": "What are Types of Nerves?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 5,
    "question": "Define Cognitive Psychology.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 6,
    "question": "Discuss relationship between Psychology and Philosophy.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 7,
    "question": "Explain Personality Structure and Development.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  }
,
  {
    "id": 1,
    "question": "What is Development Method?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 2,
    "question": "Define Criminal Psychology.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 3,
    "question": "What are Causes of Forgetting?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 4,
    "question": "Define Social Cognition.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 5,
    "question": "What is Unconscious Mind?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 6,
    "question": "Explain Brain and Mental Processes in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  },
  {
    "id": 7,
    "question": "Discuss Dreams and Dream as a Supernatural Phenomenon.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "UE-272",
    "semester": "IV",
    "Subject": "Introduction to Psychology"
  }
,
  {
    "id": 1,
    "question": "Define functions of several variables and explain partial differentiation.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 2,
    "question": "What are multiple integrals?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 3,
    "question": "Define line integrals.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 4,
    "question": "What is Green’s theorem?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 5,
    "question": "Define Fourier series and periodic functions.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 6,
    "question": "Explain Green’s theorem with applications.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 7,
    "question": "Explain Fourier series, half-range expansions and their formulas.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  }
,
  {
    "id": 1,
    "question": "Define functions of several variables.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 2,
    "question": "Explain partial differentiation.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 3,
    "question": "What are multiple integrals?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 4,
    "question": "Define Green’s and Stokes theorem.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 5,
    "question": "Define Fourier transform.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 6,
    "question": "Explain Green’s theorem and Stokes theorem in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 7,
    "question": "Explain Laplace transform and its applications.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  }
,
  {
    "id": 1,
    "question": "What are functions of several variables?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 2,
    "question": "Define partial differentiation.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 3,
    "question": "Explain multiple integrals.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 4,
    "question": "Define Fourier series and periodic functions.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 5,
    "question": "What is Z-transform?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 6,
    "question": "Explain Fourier series and its types.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 7,
    "question": "Explain Laplace transform and Z-transform with examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  }
,
  {
    "id": 1,
    "question": "Define functions of several variables.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 2,
    "question": "Explain partial differentiation.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 3,
    "question": "What are multiple integrals?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 4,
    "question": "Define Green’s theorem and Stokes theorem.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 5,
    "question": "Explain Fourier series and Fourier transform.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 6,
    "question": "Explain Green’s and Stokes theorem with applications.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 7,
    "question": "Explain Laplace transform and Z-transform in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  }
,
  {
    "id": 1,
    "question": "Define functions of several variables and their properties.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 2,
    "question": "Explain partial differentiation and its applications.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 3,
    "question": "What are multiple integrals? Explain with example.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 4,
    "question": "Define Fourier series, Fourier transform and periodic functions.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 5,
    "question": "Define Laplace transform and Z-transform.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 6,
    "question": "Explain Fourier series and half range expansions in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  },
  {
    "id": 7,
    "question": "Explain Green’s, Stokes theorem and their applications.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "SC-241",
    "semester": "IV",
    "Subject": "Multivariable Calculus"
  }
,
  {
    "id": 1,
    "question": "Define alphabet, string and language in automata theory.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 2,
    "question": "What is regular expression?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 3,
    "question": "Define finite automata.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 4,
    "question": "What is NFA and DFA?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 5,
    "question": "Define pumping lemma.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 6,
    "question": "Explain finite automata and transition graphs in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 7,
    "question": "Explain regular expressions and pumping lemma with examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  }
,
  {
    "id": 1,
    "question": "Define DFA and NFA.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 2,
    "question": "What is transition graph?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 3,
    "question": "Define regular language.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 4,
    "question": "What is CFG?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 5,
    "question": "Define Chomsky hierarchy.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 6,
    "question": "Explain context free grammar and derivation trees.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 7,
    "question": "Explain pumping lemma and non-regular languages.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  }
,
  {
    "id": 1,
    "question": "Define regular expressions and languages.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 2,
    "question": "What is NFA with epsilon transitions?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 3,
    "question": "Define PDA.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 4,
    "question": "What is Chomsky hierarchy?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 5,
    "question": "Define Turing machine.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 6,
    "question": "Explain pushdown automata and its applications.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 7,
    "question": "Explain Turing machine and universal Turing machine.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  }
,
  {
    "id": 1,
    "question": "Define finite automata and language recognition.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 2,
    "question": "What is regular expression and regular language?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 3,
    "question": "Define PDA (Push Down Automata).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 4,
    "question": "What is Chomsky hierarchy of grammars?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 5,
    "question": "Define Turing machine and its basic concept.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 6,
    "question": "Explain context free grammars and derivation trees with examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 7,
    "question": "Explain Turing machine, variations and universal Turing machine.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  }
,
  {
    "id": 1,
    "question": "Define transition graphs and finite state models.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 2,
    "question": "What is pumping lemma and its use?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 3,
    "question": "Define linear bounded automata.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 4,
    "question": "What is Post machine?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 5,
    "question": "Define decidability in automata theory.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 6,
    "question": "Explain pumping lemma and non-regular languages in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  },
  {
    "id": 7,
    "question": "Explain Turing machine, Post machine and their variations.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "DC-222",
    "Subject": "Theory of Automata"
  }
,
  {
    "id": 1,
    "question": "Define software engineering and its nature.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 2,
    "question": "What is software process?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 3,
    "question": "Define agile software development.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 4,
    "question": "What are functional requirements?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 5,
    "question": "Define UML diagrams.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 6,
    "question": "Explain software process models in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 7,
    "question": "Explain requirements engineering process with models.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  }
,
  {
    "id": 1,
    "question": "Define software engineering practice.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 2,
    "question": "What is agile process model?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 3,
    "question": "Define functional and non-functional requirements.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 4,
    "question": "What is architectural design?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 5,
    "question": "Define software testing and quality assurance.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 6,
    "question": "Explain agile software development and techniques.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 7,
    "question": "Explain software process structure and models.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  }
,
  {
    "id": 1,
    "question": "Define software process models.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 2,
    "question": "What is model driven engineering?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 3,
    "question": "Define interaction models.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 4,
    "question": "What are UML diagrams?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 5,
    "question": "Define software evolution.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 6,
    "question": "Explain architectural design and implementation process.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 7,
    "question": "Explain software testing and quality assurance in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  }
,
  {
    "id": 1,
    "question": "Define software engineering principles.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 2,
    "question": "What is agile development methodology?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 3,
    "question": "Define context models.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 4,
    "question": "What are design patterns?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 5,
    "question": "Define software configuration management.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 6,
    "question": "Explain software process improvement and models.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 7,
    "question": "Explain UML diagrams and design implementation process.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  }
,
  {
    "id": 1,
    "question": "Define professional software development.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 2,
    "question": "What is agile software development?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 3,
    "question": "Define requirements engineering process.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 4,
    "question": "What are behavioral models in software engineering?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 5,
    "question": "Define software evolution and maintenance.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 6,
    "question": "Explain software process models and agile development techniques.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  },
  {
    "id": 7,
    "question": "Explain design patterns, UML diagrams and architectural design.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "CC-212",
    "Subject": "Software Engineering"
  }
,
  {
    "id": 1,
    "question": "Define data structure and abstract data type (ADT).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 2,
    "question": "What is Big O notation?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 3,
    "question": "Define stack and its operations.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 4,
    "question": "What is recursion?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 5,
    "question": "Define queue and deque.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 6,
    "question": "Explain sorting algorithms (merge, quick, bubble).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 7,
    "question": "Explain recursion and analyze recursive algorithms with examples.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  }
,
  {
    "id": 1,
    "question": "Define linked list and its types.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 2,
    "question": "What is binary search?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 3,
    "question": "Define hashing and collision handling.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 4,
    "question": "What is tree traversal?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 5,
    "question": "Define priority queue.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 6,
    "question": "Explain sorting techniques in detail (selection, insertion, merge).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 7,
    "question": "Explain binary trees and tree traversal techniques.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  }
,
  {
    "id": 1,
    "question": "Define stack and queue with operations.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 2,
    "question": "What is graph?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 3,
    "question": "Define DFS and BFS.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 4,
    "question": "What is heap data structure?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 5,
    "question": "Define sorting algorithms.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 6,
    "question": "Explain graphs and their traversal techniques (BFS and DFS).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 7,
    "question": "Explain hashing, indexing and collision resolution techniques.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  }
,
  {
    "id": 1,
    "question": "Define abstract data types (ADT).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 2,
    "question": "What is complexity analysis?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 3,
    "question": "Define binary search tree.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 4,
    "question": "What is heap and priority queue?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 5,
    "question": "Define sorting techniques.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 6,
    "question": "Explain tree structures and tree traversal algorithms.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 7,
    "question": "Explain graphs, BFS, DFS and shortest path algorithms.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  }
,
  {
    "id": 1,
    "question": "Define recursion and its importance.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 2,
    "question": "What is hashing and indexing?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 3,
    "question": "Define binary search algorithm.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 4,
    "question": "What are sorting algorithms?",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 5,
    "question": "Define graphs and their representation.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 6,
    "question": "Explain sorting algorithms (merge, quick, heap) in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  },
  {
    "id": 7,
    "question": "Explain graphs, BFS, DFS and shortest path algorithms in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213",
    "Subject": "Data Structures and Algorithms"
  }
,
  {
    "id": 1,
    "question": "Implement stack using array and perform basic operations.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 2,
    "question": "Write a program for linear search.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 3,
    "question": "Implement queue using array.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 4,
    "question": "Write a program for bubble sort.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 5,
    "question": "Implement linked list insertion.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 6,
    "question": "Implement binary search tree insertion and traversal.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 7,
    "question": "Implement graph representation using adjacency matrix and BFS traversal.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  }
,
  {
    "id": 1,
    "question": "Implement stack using linked list.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 2,
    "question": "Write program for binary search.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 3,
    "question": "Implement queue using linked list.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 4,
    "question": "Write program for insertion sort.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 5,
    "question": "Implement doubly linked list.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 6,
    "question": "Implement heap as priority queue.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 7,
    "question": "Implement BFS and DFS on graph using adjacency list.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  }
,
  {
    "id": 1,
    "question": "Implement circular linked list.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 2,
    "question": "Write program for merge sort.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 3,
    "question": "Implement stack using arrays and linked list.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 4,
    "question": "Write program for quick sort.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 5,
    "question": "Implement linear and binary search.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 6,
    "question": "Implement AVL tree insertion and balancing.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 7,
    "question": "Implement graph traversal (BFS and DFS) with spanning trees.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  }
,
  {
    "id": 1,
    "question": "Implement stack using recursion.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 2,
    "question": "Write program for radix sort.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 3,
    "question": "Implement double ended queue (deque).",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 4,
    "question": "Write program for heap sort.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 5,
    "question": "Implement hashing with chaining.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 6,
    "question": "Implement binary search tree with insert, delete and traversal.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 7,
    "question": "Implement graph shortest path and BFS/DFS traversal.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  }
,
  {
    "id": 1,
    "question": "Implement N-dimensional arrays.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 2,
    "question": "Write program for selection sort and bubble sort.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 3,
    "question": "Implement sparse matrix operations.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 4,
    "question": "Implement AVL tree operations.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 5,
    "question": "Implement adjacency matrix and adjacency list representation of graph.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "short",
    "marks": 5,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 6,
    "question": "Implement full sorting algorithms (merge, quick, heap, radix) in detail.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  },
  {
    "id": 7,
    "question": "Implement graphs with BFS, DFS and spanning tree generation.",
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "category": "long",
    "marks": 10,
    "course_code": "CC-213L",
    "Subject": "Data Structures and Algorithms Lab"
  }
]