import { v4 as uuidv4 } from "uuid";
const semesterOne = [
  {
    question: "What is the importance of a recount essay?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-162",
    "Subject": "English Composition & Comprehension",
    "category": "short",
    "marks": 5
  },
  {
    question: "What is the difference between an explanation and informative essay?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-162",
    "Subject": "English Composition & Comprehension",
    "category": "short",
    "marks": 5
  },
  {
    question: "Discuss the significance of character development in a narrative essay.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-162",
    "Subject": "English Composition & Comprehension",
    "category": "short",
    "marks": 5
  },
  {
    question: "Discuss why punctuation is important in written communication.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-162",
    "Subject": "English Composition & Comprehension",
    "category": "short",
    "marks": 5
  },
  {
    question: "Differentiate between personal and professional application writing.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-162",
    "Subject": "English Composition & Comprehension",
    "category": "short",
    "marks": 5
  },
  {
    question: "What is a thesis statement and where is it used in an essay?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-162",
    "Subject": "English Composition & Comprehension",
    "category": "short",
    "marks": 5
  },
  {
    question: "Write a letter to your cousin/friend and discuss the importance of justice in life.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-162",
    "Subject": "English Composition & Comprehension",
    "category": "long",
    "marks": 10
  },
  {
    question: "Write an essay on 'A big salary is more important than job satisfaction/learning.'",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-162",
    "Subject": "English Composition & Comprehension",
    "category": "long",
    "marks": 10
  },
  {
    question: "Write a funny horror story. Develop a creative plot and write appropriate dialogues.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-162",
    "Subject": "English Composition & Comprehension",
    "category": "long",
    "marks": 10
  }
  ,
  {
    question: "A positive charge moving with a constant velocity v enters a region of a uniform magnetic field pointing to the top of the page. What is the direction of the magnetic force on the charge?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Define conservative field.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "If current in a conductor increases, then according to Lenz's law self-induced voltage will?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "A straight wire of length 4 m carries a current of 0.5 A. Find the magnetic field at a point along the axis of the wire at a distance of 3 m from either end of the wire.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Which law of conservation best explains and justifies the direction of induced Electromotive Force (EMF) in a circuit?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "A 2 micro-coulomb point charge is located at a distance d away from a 3 micro-coulomb point charge. What would be the ratio of F12 / F21?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "A cylindrical wire of length l moving in magnetic field B with velocity v. On which parameters does the induced emf depend?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is the relation between electric field and electric potential?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Describe Hall effect.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What will happen if you place an insulator in an external electric field?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Give some examples of diffraction in daily life.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Where do you see examples of total internal reflection in today's science?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Is light an electromagnetic wave? Explain.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "The average distance r between electron and proton in the hydrogen atom is 5.3 × 10^-11 m. What is the Coulomb force between them?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "State Ohm's law.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    "university": "University of the Punjab",
    "program": "BS Computer Science",
    "semester": "First Semester",
    "year": 2022,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "time_hours": 3,
    "total_marks": 60,
    "section": "Q1",
    "questions": 15,
    "marks_per_question": 2
  },
  {
    question: "If a conductor is moved in a magnetic field, what will be its effect? Derive a mathematical expression explaining Faraday’s Law of induction in detail.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 7
  },
  {
    question: "A spherical shell has a positive charge of 1.25 nC at its center; find flux through the whole shell.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 3
  },
  {
    question: "Derive the expression for the electric force due to a ring of positive charge q, placed along the z-axis at distance z from the test charge.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 5
  },
  {
    question: "Suppose that we have 2.10 × 10⁶ doubly charged positive ions per cubic centimeter, all moving north with a speed of 1.40 × 10⁵ m/s. Calculate the current density in magnitude and direction.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "What is an electric dipole. Find electric field due to a dipole along its perpendicular bisector.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 7
  },
  {
    question: "An electric field of 1.5 kV/m and a magnetic field of 0.44 T acts on a moving charge to have no net force. Calculate the electron speed and draw all the vectors.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 3
  },
  {
    question: "Define diffraction, give its example. Explain double slit diffraction in detail.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 5
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "Describe interference of light. Give the detailed explanation of Young’s double slit experiment.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 5
  },
  {
    question: "A ray of light makes a transition from a sample of benzene to water. What is the minimum angle the light must make with respect to the normal in order for the light to be completely reflected back into the sample of benzene? (The index of refraction for water is 1.33 and for benzene is 1.50.)",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "MS-151",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "What is difference between electric potential and electric potential energy?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is the magnitude of the electric field at the point (2i – 3j + 4k) m if the electric potential is given by V = 10xy²z²?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "What is equipotential surface, derive expression for it?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 2
  },
  {
    question: "Why electric field is zero in an isolated conductor?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 2
  },
  {
    question: "What is the Hall Effect and Hall EMP?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "How is induced electric field produced?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What conclusion can be drawn about the electric potential energy U when a positive charge q₁ and a negative charge q₂ move close together?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "A 6 μC point charge q₁ is located at a distance d away from a 3 μC point charge q₂. What is the ratio F₁₂ / F₂₁?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "If a closed surface surrounds a charge of +q, represented by six field lines, what would the net electric flux through the surface generated between two charges +2q and –q?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "What is the difference between interference generated from single slit and double slit interference?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What do you understand by diffraction of waves?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is difference between Ampere’s law and the Biot–Savart law as both are used to calculate magnetic field?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "How is current different from current density?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Define electric field and electric field intensity? Evaluate electric field intensity due to assembly of point charges? Calculate the electric field at a point “p” a distance x from the center of disk along its axis?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 6
  },
  {
    question: "Two charged concentric spherical shells have radii 10.0 cm and 15.0 cm. The charge on the inner shell is 4×10⁻⁶ C, and that on the outer shell is 2×10⁻⁶ C. Find the electric field (a) at r = 12.0 cm and (b) at r = 20.0 cm.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-159",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 4
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "What is Subject-verb Agreement? Explain its significance with examples.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "In the word formation process, what do Affixations do? Explain with examples.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "What are some key protocols of Active Listening?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "Write a Formal Letter to the Incharge of Student Affairs, requesting permission to hold a literary festival on campus.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "long",
    "marks": 15
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "long",
    "marks": 15
  },
  {
    question: "Explain the superposition principle for electric forces.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is an electric dipole moment?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "A closed surface contains two charges: +4q and –q. What is the total electric flux through the surface?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "What is equipotential surface, draw an equipotential surface.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 2
  },
  {
    question: "State Faraday’s law of induction.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is meant by a grounded conductor?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is the magnitude of the electric field at the point (–1i+2j–3k) m if the electric potential is given by V=5.00xyz²?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "State the Biot–Savart law.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is an induced magnetic field?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Explain total internal reflection.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Define diffraction.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Which of the basic equations of electromagnetism were modified by Maxwell, and what is its modified form?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Explain Lenz’s law and its importance in predicting the direction of induced current.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 2
  },
  {
    question: "A +10 μC charge is placed 0.5 m away from a –5 μC charge. What is the ratio of the force exerted on the first charge to the force exerted on the second charge?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "What is difference between patterns generated from single slit and double slit interference?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Explain Gauss’s law and apply it to find the electric field due to a uniformly charged spherical shell.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 6
  },
  {
    question: "Find the electric potential at point P, located at the center of the square of charged particles. The distance is 1.3 m, and the charges are q₁=+12 nC, q₂=–24 nC, q₃=+31 nC, q₄=+17 nC.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 4
  },
  {
    question: "Explain the potential energy of a two-charge system and its relation to the work done in assembling the system of charged particles.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 6
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 4
  },
  {
    question: "Define subject-verb agreement with examples of common errors and their corrections.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "What is affixation in word formation? Give four examples.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "Distinguish between skimming and scanning with appropriate examples.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "Briefly describe gender-neutral language with examples.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "What are the elements of effective listening and why is active listening important in communication?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "Explain with examples the key principles of effective communication (clarity, coherence, conciseness, etc.). How can these be applied in both academic and professional settings?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "long",
    "marks": 10
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "long",
    "marks": 10
  },
  {
    question: "Write a formal business email to a potential employer requesting an internship opportunity. Focus on structure, tone, and clarity.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "long",
    "marks": 10
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  }
  ,
  {
    question: "Define subject-verb agreement with examples of common errors and their corrections.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "What is affixation in word formation? Give four examples.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "Distinguish between skimming and scanning with appropriate examples.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "Briefly describe gender-neutral language with examples.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "What are the elements of effective listening and why is active listening important in communication?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "Explain with examples the key principles of effective communication (clarity, coherence, conciseness, etc.). How can these be applied in both academic and professional settings?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "long",
    "marks": 10
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "long",
    "marks": 10
  },
  {
    question: "Write a formal business email to a potential employer requesting an internship opportunity. Focus on structure, tone, and clarity.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Spring",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "long",
    "marks": 10
  }
  ,
  {
    question: "An aircraft seam requires 25 rivets. The seam will have to be reworked if any of these rivets is defective. Suppose rivets are defective independently of one another, each with the same probability. If 20% of all seams need reworking, what is the probability that a rivet is defective?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "The cumulative probability density function is F(x) = {0, x < -1; (1/4)(x+1), -1 ≤ x < 2; 1, x ≥ 2}. Find P(0 < x ≤ 1).",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "The random variable X, representing the number of cherries in a cherry puff, has the following probability distribution: X={4,5,6,7}, P(X)={0.3,0.4,0.2,0.1}. Find the mean μx and the variance σx of the mean X̄ for random samples of 30 cherry puffs.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "Find P(-z0.85 < z < z0.85).",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "For 5 pairs of observations the following results are obtained: ΣX=15, ΣY=25, ΣX²=55, ΣY²=135, ΣXY=83. Find the equation of the lines of regression and estimate the value of X on the first line when Y=12 and value of Y on the second line when X=8.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "The joint p.d.f of f(X,Y) is given by f(X,Y) = (1/4)(1+xy), |x|<1, |y|<1; 0 otherwise. Check whether X and Y are independent?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "long",
    "marks": 10
  },
  {
    question: "From past experiences a stockbroker believes that under present economic conditions a customer will invest in tax-free bonds with probability 0.6, mutual funds with probability 0.3, and both with probability 0.15. Find the probability that a customer will invest (a) in either tax-free bonds or mutual funds, (b) in neither tax-free bonds nor mutual funds.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 10
  },
  {
    question: "The CEO of a light bulbs manufacturing company claims that an average light bulb lasts 300 days. A researcher randomly selects 15 bulbs for testing. The sampled bulbs last an average of 290 days, with a standard deviation of 50 days. If the CEO’s claim were true, what is the probability that 15 randomly selected bulbs would have an average life of no more than 290 days?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 10
  }
  ,
  {
    question: "How many permutations of 4 different letters are there, chosen from the twenty six letters of the alphabet?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "One card is drawn from a deck of 52 cards, well-shuffled. Calculate the probability that the card will not be an ace.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "Find the range and coefficient of range of the data: 63, 89, 98, 125, 79, 108, 117, 687.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "Given the normally distributed variable X with mean 18 and standard deviation 2.5, find the value of k such that P(X < k) = 0.22367.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "A teacher asked the students to complete 60 pages of a record notebook. Eight students have completed only 32, 35, 37, 30, 33, 36, 35 and 37 pages. Find the standard deviation of the pages yet to be completed by them.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "Let X be a continuous random variable with PDF f(x) = {x, 0 ≤ x ≤ 1; 0, otherwise}. Find the expected value of X.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "A large chain retailer purchases a certain kind of electronic device from a manufacturer. The manufacturer indicates that the defective rate of the device is 3%. The inspector of the retailer randomly picks 20 items from a shipment. What is the probability that there will be at least one defective item among these 20?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 10
  },
  {
    question: "Given a random variable X having a normal distribution with mean 50 and standard deviation 10, find the probability that X assumes a value between 45 and 65.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 10
  },
  {
    question: "Calculate mean deviation and coefficient of mean deviation from mean in continuous grouped case, showing the weights of 60 apples. Also draw the histogram of the data. Weights (grams): 65–84, 85–104, 105–124, 125–144, 145–164, 165–184, 185–204. Frequencies: 09, 10, 17, 13, 04, 05, 02.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "MS-152",
    "Subject": "Probability & Statistics",
    "category": "long",
    "marks": 10
  }
  ,
  {
    question: "Each of 11 linguists translates at least one of the languages Urdu and Punjabi into English. The numbers who translate only Urdu or Punjabi are both odd primes. More linguists translate Burmese than Amharic. How many can translate Urdu?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 5
  },
  {
    question: "Find Big-O of the function 5x² + 10x log x.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "List all the subsets of the set {1, 2, 3}. How many subsets are there of a set with n elements?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "Find the number of distinct positive integer multiples of 2, 3, 5, 7 or 11 not exceeding 3000.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "Find a general function for the following sequence: 0, 2, 3, 5, 8, 6.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "How many edges are there in a complete graph with 6 vertices?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 5
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 10
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 10
  },
  {
    question: "Prove by mathematical induction that the sum of the first n positive odd integers is n², that is, 1 + 3 + 5 + ⋯ + (2n − 1) = n².",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 5
  },
  {
    question: "Translate each of these statements into logical expressions: i) A student in your school has lived in Vietnam. ii) A student in your school knows Java, Prolog, and C++.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 5
  }
  ,
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 3
  },
  {
    question: "Evaluate the Cartesian product (E₁ ⊕ E₂).",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "Find the first seven terms of given sequence a(n) = (3ⁿ + 1) where n ≥ 1.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "Let f : Z → Z be such that f(x) = x + 3. Is f invertible, and if it is, what is its inverse?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 2
  },
  {
    question: "Find the greatest common divisor (345,345) using trial division algorithm.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "Prove whether the given statement (p → q) ∧ (q → r) → (p → r) is a tautology or not using laws of logic.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 2
  },
  {
    question: "Find the least common multiple (LCM) of 200, 25 and 1457.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "Evaluate the following summation using x=2, y=3, b=2.5 and c=3: Σ(i=1 to 3) Σ(j=1 to 2) x_i y_j + 4b_i + 2c.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "What rules of inference are used in the given argument: 'Linda is an excellent swimmer. If Linda is an excellent swimmer then she can work as a lifeguard. Therefore, Linda can work as a lifeguard.'",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 2
  },
  {
    question: "Prove that if n is a positive integer, then n² is odd if and only if 5n + 6 is odd using contrapositive.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 3
  },
  {
    question: "What is the prime factorization of 2022?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "Use mathematical induction to prove that for any positive integer number n, n² − n is divisible by 3.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 8
  },
  {
    question: "Determine the chromatic number of given Graph and then calculate the degree of each vertex. Furthermore, determine whether the graph contains Euler circuit/Euler path/Hamiltonian circuit/path. Clearly highlight the path and/or circuit if any. Also, draw W₅ graph.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 13
  },
  {
    question: "Using counting and probability concepts: (a) Find the minimum number of people required in a fruit shop to be sure that at least six will receive the same fruits, if there are five possible types of fruits. (b) How many ways are there to select six players from a 13-member football team to make a trip to a match at Qatar? (c) How many different strings can be made by reordering the letters of word 'KINDERGARTEN'? (d) How many numbers from 1500 to 2500 are divisible by 7 or 9?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 9
  }
  ,
  {
    question: "Translate the following statement into logic: ∃x∃y (x > 0) ∨ (y > 0) → (xy < 0).",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is the least common multiple and greatest common divisor of 2³×3²×5⁴ and 2⁵×3³×5²?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "Find that sum of rational and irrational number will always be irrational.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 2
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 5
  },
  {
    question: "Evaluate the following relations: (a) {1, 2, 3, 4, 5, 6, 118} (b) {1, 2, 3, 4, 5, 6, 118}.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 5
  },
  {
    question: "Evaluate following function: f(x) = 3x² + 2x + 1, for x = 1, 2, 3.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 3
  },
  {
    question: "What is the minimum number of students required in a discrete structures class to be sure that at least two students get the same grade, if there are five grades, A, B, C, D, and F?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 3
  },
  {
    question: "The argument 'All happy men are married. John is happy. Therefore, John is married.' Write symbolic form of inference.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 3
  },
  {
    question: "Use Mathematical Induction to prove the following formula for non-negative integers n: 1 + 3 + 5 + ... + (2n - 1) = n².",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 8
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 13
  },
  {
    question: "Using counting and probability concepts: (a) How many different strings can be made by reordering the letters of the word SUCCESS? (b) Suppose that there are eight runners in a race. The winner receives a gold medal, the second place receives a silver medal, and the third-place finisher receives a bronze medal. How many different ways are there to award these medals? (c) How many permutations of the letters ABCDEFGH contain the string ABC? (d) A group of 30 people have been trained as IT specialists to go to a specific assignment. When they are to select a crew of six people to go on this assignment, how many different selections are possible? (e) What is the chance that after rolling a die, we’ll get value greater than three?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2024,
    "term": "Spring",
    "course_code": "CC-111",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 9
  }
  ,
  {
    question: "What is difference between System Software and Application Software?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is meant by Expansion Slots?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    question: "What are Registers? Which register is used to hold address of Next Executable Instruction?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is Pipelining?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is purpose of VeriChip?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    question: "What are Multimedia elements?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is difference between HTML and XHTML?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    question: "How will you differentiate between Half Duplex and Full Duplex Transmission?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    question: "Name two commands used to create a file in Linux Terminal.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    question: "List the problems faced by humanity which could be solved using Information Technology.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    question: "Convert 1001110 in base 2 into a decimal number.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "What is a Hot-swappable device?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 2
  },
  {
    question: "List several types of networking hardware and explain the purpose of each.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 10
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 10
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2021,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 10
  }
  ,
  {
    question: "Discuss output devices briefly.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 5
  },
  {
    question: "Discuss briefly Fiber-Optic Cable.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 5
  },
  {
    question: "What are the IP Addresses and Domain Names?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 5
  },
  {
    question: "Define a computer and describe its primary operations.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 5
  },
  {
    question: "What is Cache Memory? And its role in computer system.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 5
  },
  {
    question: "Discuss the various types of optical discs available today and how they differ from each other.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 5
  },
  {
    question: "Discuss briefly Network Topologies with figures.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 10
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 10
  },
  {
    question: "Explain the different functions of an operating system.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2023,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 10
  }
  ,
  {
    question: "What is a communication protocol in computer networks?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 3
  },
  {
    question: "What is a disk pack?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 3
  },
  {
    question: "What is the printing mechanism of a drum printer?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 3
  },
  {
    question: "Differentiate between star and bus topology.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 3
  },
  {
    question: "Differentiate between inkjet printers and dot matrix printers.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 3
  },
  {
    question: "What are the types of system software?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 3
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 3
  },
  {
    question: "What are plotters and where they are used?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 3
  },
  {
    question: "Differentiate between synchronous and asynchronous data transmission.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 3
  },
  {
    question: "What is distributed computing?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "short",
    "marks": 3
  },
  {
    question: "Write a note on input devices. Discuss various input devices and their applications.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 5
  },
  {
    question: "Discuss the brief history of internet. Also discuss basic services of the internet.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 5
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 5
  },
  {
    question: "What is ROM? Discuss the importance of ROM and its various types.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 5
  },
  {
    question: "Discuss the three data transmission modes with examples.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 4
  },
  {
    question: "Write a detailed note on data transmission media.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2022,
    "term": "Fall",
    "course_code": "GE-161",
    "Subject": "Introduction to ICT",
    "category": "long",
    "marks": 6
  }
  ,
  {
    question: "Differentiate between the following terms by giving suitable examples of each: (i) Discrete & continuous random variables, (ii) Type-I & Type-II errors, (iii) Mutually exclusive & non-mutually exclusive events.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "MS-251",
    "Subject": "Probability & Statistics",
    "category": "short",
    "marks": 6
  },
  {
    question: "An electric firm manufactures light bulbs that have mean lifetime of 800 hours with standard deviation of 40 hours. If a random sample of 30 bulbs have an average life of 785 hours, then test the hypothesis that μ = 800 against the alternative that μ < 800.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "MS-251",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 6
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "MS-251",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 6
  },
  {
    question: "Briefly explain one-tailed and two-tailed tests with the help of examples.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "MS-251",
    "Subject": "Probability & Statistics",
    "category": "short",
    "marks": 6
  },
  {
    question: "Suppose that in a senior college class of 500 students it is found that 210 smoke, 258 drink alcoholic beverages, 216 eat between meals, and 83 eat between meals and drink alcoholic beverages. If a member of this senior class is selected at random, find the probability that the person: (i) neither smokes nor drinks alcoholic beverages, (ii) neither smokes nor eats between meals.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "MS-251",
    "Subject": "Probability & Statistics",
    "category": "numerical",
    "marks": 6
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "MS-251",
    "Subject": "Probability & Statistics",
    "category": "long",
    "marks": 10
  }
  ,
  {
    question: "State Coulomb’s law and mention its limitations.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is the difference between electric potential and electric potential energy?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Calculate the electric flux through a spherical surface enclosing a charge of 3 μC.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "What is meant by quantization of charge?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Why do electric field lines never intersect?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is polarization of a dielectric?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Why does Hall voltage appear across a current-carrying conductor placed in a magnetic field?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Define electric current. What is meant by current density?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "A current of 5 A flows in a long straight wire. Find the magnetic field placed at a distance of 10 cm.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "numerical",
    "marks": 2
  },
  {
    question: "State Biot–Savart law.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "How Lenz’s law determines the direction of the induced current?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is displacement current?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Define refractive index.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Differentiate between interference and diffraction.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "What is thin film interference?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "short",
    "marks": 2
  },
  {
    question: "Derive the electric field due to a charged disk.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 5
  },
  {
    question: "Derive the expression for the electric field due to an electric dipole.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 5
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 5
  },
  {
    question: "Explain Faraday’s experiments and derive Faraday’s law of electromagnetic induction.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 5
  },
  {
    question: "Explain polarization of electromagnetic waves. Describe different methods of producing polarized light.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-169",
    "Subject": "Applied Physics",
    "category": "long",
    "marks": 6
  },
  {
    question: "A, B, C, D are sets such that A∪B = C∪D, and both A∩B and C∩D are empty. Show by examples that A∩C and B∩D can be empty.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 5
  },
  {
    question: "For the relation (a,b) ∈ R if a < 3b on N, determine whether the relation is reflexive, symmetric, or transitive.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 5
  },
  {
    question: "Check if the function y = x² from N to N is one-to-one correspondence?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 5
  },
  {
    question: "Find (210, 858). Determine integers x and y such that (210, 858) = 210x + 858y. Hence, give the general solution of the equation in integers x and y.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "Determine whether the following sequence can represent the degree sequence of a simple graph: (3,3,2,2,2,2).",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "short",
    "marks": 5
  },
  {
    question: "The chairs of an auditorium are to be labeled with an uppercase English letter followed by a positive integer not exceeding 100. What is the largest number of chairs that can be labeled differently?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 5
  },
  {
    question: "The sequence aₙ is defined recursively for n ∈ N by a₁ = 3, a₂ = 5, and aₙ = 3aₙ₋₁ − 2aₙ₋₂ for n ≥ 3. Prove that aₙ = 2ⁿ + 1 for every n ∈ N.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 10
  },
  {
    question: "Calculate the number of distinct natural numbers not exceeding 1000 which are multiples of 10, 15, or 35.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "numerical",
    "marks": 10
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GE-167",
    "Subject": "Discrete Structures",
    "category": "long",
    "marks": 10
  }
  ,
  {
    question: "What is the difference between a phrase and a clause? Give examples of each.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "Define collocation and illustrate with four examples used in academic writing.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "Differentiate between denotation and connotation with suitable examples.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "What is paraphrasing? Why is it important in academic writing?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "Mention the features of non-verbal communication. How can gestures complement verbal messages?",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "short",
    "marks": 5
  },
  {
    question: "Discuss the barriers to effective communication and suggest strategies to overcome them, citing examples from daily academic life.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "long",
    "marks": 10
  },
  {
    "index": true,
    id: uuidv4(),
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "long",
    "marks": 10
  },
  {
    question: "Write a formal letter to the editor of a national newspaper expressing your opinion about the looming climate / smog crisis in Pakistan. Focus on coherence, tone, and persuasive reasoning.",
    id: uuidv4(),
    "index": true,
    "trim": true,
    "type": "past-paper",
    "year": 2025,
    "term": "Fall",
    "course_code": "GENG-101",
    "Subject": "Functional English",
    "category": "long",
    "marks": 10
  },
]


export { semesterOne }